import type { Experience } from "./types";

/**
 * Twenty-seven bookable experiences across all ten destinations, covering
 * every category the marketplace filters on: culture, history, adventure,
 * food, nature, wellness, nightlife and water.
 */
export const experiences: Experience[] = [
  {
    id: "exp-giza-sunrise",
    slug: "giza-pyramids-at-sunrise",
    name: { en: "Giza Pyramids at Sunrise", ar: "أهرامات الجيزة عند الشروق" },
    destinationSlug: "giza",
    category: "history",
    travelStyles: ["history", "family", "romantic"],
    environment: "outdoor",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 240,
    priceFrom: 78,
    privateSupplement: 45,
    rating: 4.9,
    reviewCount: 412,
    maxGroupSize: 12,
    minAge: null,
    summary: {
      en: "Enter the plateau as the gates open, with an Egyptologist and two hours before the coaches.",
      ar: "ادخل الهضبة لحظة فتح البوابات، ومعك مرشد متخصص في علم المصريات، وأمامك ساعتان كاملتان قبل وصول الحافلات.",
    },
    description: {
      en: "The plateau opens at eight and empties of atmosphere by ten, so this tour starts at seven. You walk the Great Pyramid's north face while the light is still low, take the panorama point before it fills, and finish at the Sphinx from the valley temple causeway. An Egyptologist stays with the group throughout and answers the questions guidebooks skip.",
      ar: "تفتح الهضبة أبوابها في الثامنة، وبحلول العاشرة يكون الزحام قد أفسد جوّها، لذلك تبدأ هذه الجولة في السابعة. تمشي بمحاذاة الواجهة الشمالية للهرم الأكبر والشمس ما زالت منخفضة، وتبلغ نقطة البانوراما قبل أن تمتلئ، وتختم عند أبي الهول قادمًا من طريق معبد الوادي. يرافق المجموعة طوال الوقت مرشد متخصص في علم المصريات، يجيب عن الأسئلة التي تقفز عنها كتب الإرشاد.",
    },
    schedule: { en: "Daily, 07:00 pickup", ar: "يوميًا، الاصطحاب من الفندق في 07:00" },
    meetingPoint: { en: "Hotel pickup in Giza or Cairo", ar: "اصطحاب من فندقك في الجيزة أو القاهرة" },
    inclusions: {
      en: ["Licensed Egyptologist guide", "Hotel transfers in an air-conditioned vehicle", "Plateau entry ticket", "Bottled water"],
      ar: ["مرشد مرخّص متخصص في علم المصريات", "انتقالات من الفندق وإليه بسيارة مكيّفة", "تذكرة دخول الهضبة", "مياه معبأة"],
    },
    exclusions: {
      en: ["Entry inside the Great Pyramid", "Camel or horse rides", "Gratuities"],
      ar: ["دخول الهرم الأكبر من الداخل", "ركوب الجمال أو الخيل", "الإكراميات"],
    },
    whatToBring: {
      en: ["Closed shoes for sand and rubble", "Hat and sunscreen", "Small notes for the photography fee"],
      ar: ["حذاء مغلق للرمل والحصى", "قبعة وواقٍ من الشمس", "نقود من فئات صغيرة لرسم التصوير"],
    },
    accessibility: {
      en: "The plateau road is paved and drivable, so wheelchair users can reach every viewpoint. Entering the pyramid interior is not step-free.",
      ar: "طريق الهضبة مرصوف وتسلكه السيارات، فيستطيع مستخدمو الكراسي المتحركة بلوغ كل نقاط المشاهدة. أما دخول الهرم من الداخل فيتطلب صعود درجات ونزولها.",
    },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/giza-sunrise.webp", alt: { en: "Riders below the pyramid of Khafre", ar: "خيّالة عند سفح هرم خفرع" } },
    gallery: [
      {
        src: "/images/experiences/giza-sunrise-01.webp",
        alt: { en: "The Great Pyramid's blocks, with visitors for scale", ar: "أحجار الهرم الأكبر، والزوار بجوارها يُظهرون ضخامتها" },
      },
      {
        src: "/images/experiences/giza-sunrise-02.webp",
        alt: { en: "The Sphinx with the Great Pyramid behind it", ar: "أبو الهول والهرم الأكبر خلفه" },
      },
    ],
    accent: "#c85f26",
  },
  {
    id: "exp-gem-tour",
    slug: "grand-egyptian-museum-guided",
    name: { en: "Grand Egyptian Museum, Guided", ar: "المتحف المصري الكبير بصحبة مرشد" },
    destinationSlug: "giza",
    category: "culture",
    travelStyles: ["history", "family", "luxury"],
    environment: "indoor",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 270,
    priceFrom: 64,
    privateSupplement: 40,
    rating: 4.8,
    reviewCount: 356,
    maxGroupSize: 14,
    minAge: null,
    summary: {
      en: "Half a day in the world's largest archaeological museum, with a route that skips the queue-shaped mistakes.",
      ar: "نصف يوم في أكبر متحف للآثار في العالم، على مسار مدروس يجنّبك الطوابير التي يقع فيها الجميع.",
    },
    description: {
      en: "Fifty thousand objects will exhaust anyone without a plan. Your guide takes the grand staircase chronologically, spends the middle of the visit in the two Tutankhamun galleries, and leaves the solar boat for the end. Expect roughly four hours inside with a coffee break at the atrium.",
      ar: "خمسون ألف قطعة أثرية كفيلة بإنهاك من يدخل بلا خطة. يصعد بك المرشد الدرج الكبير بترتيب العصور، ويخصص منتصف الزيارة لقاعتي توت عنخ آمون، ويترك مركب الشمس إلى النهاية. احسب نحو أربع ساعات في الداخل، تتخللها استراحة قهوة في البهو.",
    },
    schedule: { en: "Daily except Tuesday, 09:30 and 13:30", ar: "يوميًا عدا الثلاثاء، 09:30 و13:30" },
    meetingPoint: { en: "Museum main entrance, Giza", ar: "المدخل الرئيسي للمتحف، الجيزة" },
    inclusions: {
      en: ["Egyptologist guide", "Museum entry ticket", "Audio headsets for larger groups"],
      ar: ["مرشد متخصص في علم المصريات", "تذكرة دخول المتحف", "سماعات للمجموعات الكبيرة"],
    },
    exclusions: { en: ["Transfers", "Food and drink", "Tutankhamun gallery photography fee"], ar: ["الانتقالات", "الطعام والشراب", "رسم التصوير في قاعتي توت عنخ آمون"] },
    whatToBring: { en: ["Comfortable shoes", "A light layer for the air conditioning"], ar: ["حذاء مريح", "سترة خفيفة، فالتكييف بارد"] },
    accessibility: { en: "Step-free throughout, with lifts to every level and wheelchairs available at the entrance.", ar: "لا درج في أي جزء منه، ومصاعد تصل إلى كل الطوابق، وكراسٍ متحركة متاحة عند المدخل." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/gem-atrium.webp", alt: { en: "The museum atrium and colossal statue", ar: "بهو المتحف والتمثال الضخم" } },
    gallery: [
      {
        src: "/images/experiences/gem-atrium-01.webp",
        alt: { en: "The grand staircase, lined with royal statues", ar: "الدرج الكبير وعلى جانبيه تماثيل الملوك" },
      },
      {
        src: "/images/experiences/gem-atrium-02.webp",
        alt: { en: "Daylight through the museum's glass wall", ar: "ضوء النهار عبر الواجهة الزجاجية للمتحف" },
      },
    ],
    accent: "#a8853b",
  },
  {
    id: "exp-khan-food",
    slug: "khan-el-khalili-food-walk",
    name: { en: "Khan el-Khalili Food Walk", ar: "جولة طعام في خان الخليلي" },
    destinationSlug: "cairo",
    category: "food",
    travelStyles: ["family", "history"],
    environment: "urban",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 210,
    priceFrom: 52,
    privateSupplement: 30,
    rating: 4.9,
    reviewCount: 288,
    maxGroupSize: 10,
    minAge: null,
    summary: {
      en: "Seven tastings through the old market, from koshary counters to the oldest coffee house in Cairo.",
      ar: "سبع وقفات للتذوق في السوق القديم، تبدأ من محلات الكشري وتنتهي في أقدم مقهى بالقاهرة.",
    },
    description: {
      en: "A walking route through Fatimid Cairo built entirely around what people actually eat: koshary, hawawshi off the grill, fresh sugarcane juice, feteer sweet and savoury, and mint tea at El Fishawy, which has been open since 1773. Enough food to replace dinner.",
      ar: "جولة على الأقدام في القاهرة الفاطمية مبنية كلها على ما يأكله الناس هنا حقًا: كشري، وحواوشي ساخن من الفرن، وعصير قصب طازج، وفطير مشلتت بالحلو والمالح، وشاي بالنعناع في الفيشاوي الذي لم يغلق أبوابه منذ 1773. كمية تُغنيك عن العشاء.",
    },
    schedule: { en: "Sunday to Thursday, 17:00", ar: "من الأحد إلى الخميس، 17:00" },
    meetingPoint: { en: "Al-Hussein Square, by the mosque gate", ar: "ميدان الحسين، عند باب المسجد" },
    inclusions: { en: ["All seven tastings", "Local food guide", "Tea at El Fishawy"], ar: ["وقفات التذوق السبع كلها", "مرشد محلي متخصص في الطعام", "شاي في الفيشاوي"] },
    exclusions: { en: ["Transfers", "Additional drinks", "Shopping"], ar: ["الانتقالات", "المشروبات الإضافية", "التسوق"] },
    whatToBring: { en: ["An empty stomach", "Cash for souvenirs"], ar: ["معدة فارغة", "نقود للهدايا التذكارية"] },
    accessibility: { en: "Cobbled and busy underfoot. Tell us in advance and we will adjust the route for limited mobility.", ar: "الأرض مرصوفة بالحجارة والزحام شديد. إن كانت الحركة صعبة على أحد المشاركين فأخبرنا مسبقًا لنعدّل المسار." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/khan-food.webp", alt: { en: "Street food stall in the old market", ar: "بسطة طعام في السوق القديم" } },
    gallery: [
      {
        src: "/images/experiences/khan-food-01.webp",
        alt: { en: "The bazaar lanes after dark", ar: "أزقة الخان بعد حلول الظلام" },
      },
      {
        src: "/images/experiences/khan-food-02.webp",
        alt: { en: "Koshary, the dish Cairo argues about", ar: "الكشري، الطبق الذي لا تتفق القاهرة على أفضل من يصنعه" },
      },
    ],
    accent: "#c85f26",
  },
  {
    id: "exp-muizz-night",
    slug: "islamic-cairo-night-walk",
    name: { en: "Islamic Cairo After Dark", ar: "القاهرة الإسلامية بعد الغروب" },
    destinationSlug: "cairo",
    category: "culture",
    travelStyles: ["history", "romantic"],
    environment: "urban",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 180,
    priceFrom: 44,
    privateSupplement: 28,
    rating: 4.8,
    reviewCount: 197,
    maxGroupSize: 12,
    minAge: null,
    summary: {
      en: "Al-Muizz Street lit and closed to cars, from Bab al-Futuh to the Ghuri complex.",
      ar: "شارع المعز بأضوائه وقد أُغلق أمام السيارات، من باب الفتوح إلى مجموعة الغوري.",
    },
    description: {
      en: "One kilometre of continuous medieval architecture, walked in the two hours when it looks its best. Minarets are floodlit, the street is pedestrianised, and a rooftop stop above the Qalawun complex gives you the skyline that put the phrase 'city of a thousand minarets' into circulation.",
      ar: "كيلومتر كامل من العمارة الإسلامية المتصلة، تقطعه مشيًا في الساعتين اللتين يبدو فيهما في أجمل حالاته. المآذن مضاءة بالكشافات، والشارع خالٍ من السيارات، ووقفة على سطح يطل على مجموعة قلاوون تريك الأفق الذي جعل الناس يسمّون القاهرة «مدينة الألف مئذنة».",
    },
    schedule: { en: "Daily, 18:30", ar: "يوميًا، 18:30" },
    meetingPoint: { en: "Bab al-Futuh gate", ar: "باب الفتوح" },
    inclusions: { en: ["Guide", "Mosque entries where ticketed", "Rooftop tea"], ar: ["مرشد", "تذاكر دخول المساجد التي تتطلبها", "شاي على السطح"] },
    exclusions: { en: ["Transfers", "Dinner"], ar: ["الانتقالات", "العشاء"] },
    whatToBring: { en: ["Shoulders and knees covered", "A scarf for mosque visits"], ar: ["ملابس تغطي الكتفين والركبتين", "وشاح لزيارة المساجد"] },
    accessibility: { en: "Mostly flat and paved. Two mosque courtyards have a single step.", ar: "المسار مستوٍ ومرصوف في معظمه، وفي صحنَي مسجدين درجة واحدة فقط." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/muizz-night.webp", alt: { en: "The lit minarets of Al-Azhar, a few steps from Al-Muizz Street", ar: "مآذن الأزهر مضاءة، على خطوات من شارع المعز" } },
    gallery: [
      {
        src: "/images/experiences/muizz-night-01.webp",
        alt: { en: "Minarets lit along the street at night", ar: "المآذن مضاءة على امتداد الشارع ليلًا" },
      },
      {
        src: "/images/experiences/muizz-night-02.webp",
        alt: { en: "Mosque facades under the evening floodlights", ar: "واجهات المساجد تحت أضواء المساء" },
      },
    ],
    accent: "#a8853b",
  },
  {
    id: "exp-nile-dinner",
    slug: "nile-dinner-cruise-cairo",
    name: { en: "Nile Dinner Cruise", ar: "رحلة عشاء نيلية" },
    destinationSlug: "cairo",
    category: "nightlife",
    travelStyles: ["romantic", "family", "luxury"],
    environment: "water",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 150,
    priceFrom: 58,
    privateSupplement: 120,
    rating: 4.6,
    reviewCount: 524,
    maxGroupSize: 60,
    minAge: null,
    summary: {
      en: "Two hours on the water with an open buffet, live oud and the city lit on both banks.",
      ar: "ساعتان على النيل مع بوفيه مفتوح وعزف عود حيّ، والمدينة مضاءة على الضفتين.",
    },
    description: {
      en: "A calm, unhurried loop between Zamalek and Garden City while dinner is served. The set includes a live oud player and a tanoura dancer, and the upper deck stays open all evening for anyone who would rather watch the bridges than the show.",
      ar: "جولة هادئة على مهل بين الزمالك وجاردن سيتي بينما يُقدَّم العشاء. البرنامج الفني عازف عود وراقص تنورة، ويظل السطح العلوي مفتوحًا طوال السهرة لمن يفضّل مشاهدة الكباري على متابعة العرض.",
    },
    schedule: { en: "Daily, 19:30 and 21:45", ar: "يوميًا، 19:30 و21:45" },
    meetingPoint: { en: "Boat mooring, Corniche El Nil, Garden City", ar: "مرسى المركب، كورنيش النيل، جاردن سيتي" },
    inclusions: { en: ["Open buffet dinner", "Live music and tanoura show", "Soft drinks"], ar: ["عشاء من بوفيه مفتوح", "موسيقى حية وعرض تنورة", "مشروبات غازية"] },
    exclusions: { en: ["Hotel transfers", "Alcoholic drinks"], ar: ["الانتقالات من الفندق", "المشروبات الكحولية"] },
    whatToBring: { en: ["Smart casual dress", "A light jacket in winter"], ar: ["ملابس أنيقة غير رسمية", "سترة خفيفة في الشتاء"] },
    accessibility: { en: "A short gangway with a handrail. Step-free once aboard the main deck.", ar: "معبر صعود قصير مزوّد بدرابزين، ولا درج بعده على السطح الرئيسي." },
    cancellation: { en: "Free cancellation up to 48 hours before", ar: "إلغاء مجاني حتى 48 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/nile-dinner.webp", alt: { en: "The Nile at dusk in Cairo", ar: "النيل عند الغسق في القاهرة" } },
    gallery: [
      {
        src: "/images/experiences/nile-dinner-01.webp",
        alt: { en: "The Cairo Tower above the river at night", ar: "برج القاهرة فوق النهر ليلًا" },
      },
      {
        src: "/images/experiences/nile-dinner-02.webp",
        alt: { en: "Boats moored along the lit corniche", ar: "مراكب راسية على الكورنيش المضاء" },
      },
    ],
    accent: "#2a719a",
  },
  {
    id: "exp-saqqara",
    slug: "saqqara-and-dahshur-day",
    name: { en: "Saqqara and Dahshur Day", ar: "يوم في سقارة ودهشور" },
    destinationSlug: "giza",
    category: "history",
    travelStyles: ["history"],
    environment: "outdoor",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 420,
    priceFrom: 88,
    privateSupplement: 55,
    rating: 4.9,
    reviewCount: 214,
    maxGroupSize: 12,
    minAge: null,
    summary: {
      en: "The Step Pyramid, the Bent Pyramid and the Red Pyramid, all without the Giza crowds.",
      ar: "الهرم المدرج والهرم المنحني والهرم الأحمر، وكلها بعيدة عن زحام الجيزة.",
    },
    description: {
      en: "Djoser's Step Pyramid is the oldest stone building on earth and the necropolis around it holds mastabas with carving far finer than anything at Giza. Dahshur adds the two pyramids where the geometry was worked out, and you can walk down into the Red Pyramid with no queue at all.",
      ar: "هرم زوسر المدرج أقدم بناء حجري على وجه الأرض، والجبّانة المحيطة به مليئة بمصاطب نقوشها أدق بكثير من كل ما في الجيزة. ثم تأتي دهشور بالهرمين اللذين تعلّم فيهما المصريون هندسة الهرم الحقيقي، وتنزل إلى قلب الهرم الأحمر دون طابور واحد.",
    },
    schedule: { en: "Daily, 08:00 pickup", ar: "يوميًا، الاصطحاب من الفندق في 08:00" },
    meetingPoint: { en: "Hotel pickup in Giza or Cairo", ar: "اصطحاب من فندقك في الجيزة أو القاهرة" },
    inclusions: { en: ["Egyptologist guide", "All site entry tickets", "Air-conditioned transfers", "Lunch"], ar: ["مرشد متخصص في علم المصريات", "تذاكر دخول كل المواقع", "انتقالات بسيارة مكيّفة", "غداء"] },
    exclusions: { en: ["Gratuities", "Photography fees inside tombs"], ar: ["الإكراميات", "رسوم التصوير داخل المقابر"] },
    whatToBring: { en: ["Sun protection", "Water", "Shoes you can climb a shaft in"], ar: ["واقٍ من الشمس", "ماء", "حذاء يصلح للنزول في ممر منحدر"] },
    accessibility: { en: "Site paths are sandy and uneven. Pyramid interiors involve a steep, low, ducked descent.", ar: "ممرات المواقع رملية وغير مستوية، والدخول إلى الأهرامات نزول شديد الانحدار في ممر منخفض تسير فيه منحنيًا." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/saqqara.webp", alt: { en: "The Step Pyramid of Djoser", ar: "هرم زوسر المدرج" } },
    gallery: [
      {
        src: "/images/experiences/saqqara-01.webp",
        alt: { en: "Djoser's step pyramid, the first of them all", ar: "هرم زوسر المدرج، أول الأهرامات" },
      },
      {
        src: "/images/experiences/saqqara-02.webp",
        alt: { en: "The Bent Pyramid at Dahshur, still wearing its casing", ar: "الهرم المنحني في دهشور، وما زال يحتفظ بكسوته الخارجية" },
      },
    ],
    accent: "#9a7a54",
  },
  {
    id: "exp-alex-greco",
    slug: "alexandria-greco-roman-day",
    name: { en: "Greco-Roman Alexandria", ar: "الإسكندرية اليونانية الرومانية" },
    destinationSlug: "alexandria",
    category: "history",
    travelStyles: ["history", "family"],
    environment: "urban",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 360,
    priceFrom: 62,
    privateSupplement: 40,
    rating: 4.7,
    reviewCount: 168,
    maxGroupSize: 12,
    minAge: null,
    summary: {
      en: "Catacombs, Pompey's Pillar, the Roman theatre and Qaitbay Citadel in one well-ordered day.",
      ar: "مقابر كوم الشقافة وعمود السواري والمسرح الروماني وقلعة قايتباي في يوم واحد مرتّب بعناية.",
    },
    description: {
      en: "Alexandria's ancient layer is scattered across the modern city, which is why doing it with a driver and a route makes the difference. The day ends at Qaitbay on the harbour wall, standing on the foundations of the lighthouse.",
      ar: "آثار الإسكندرية القديمة متناثرة تحت المدينة الحديثة وبينها، ولهذا يصنع السائق والمسار المدروس كل الفرق. ينتهي اليوم في قلعة قايتباي على حافة الميناء، وأنت واقف فوق أساسات المنارة القديمة.",
    },
    schedule: { en: "Daily except Monday, 09:00", ar: "يوميًا عدا الاثنين، 09:00" },
    meetingPoint: { en: "Hotel pickup in Alexandria", ar: "اصطحاب من فندقك في الإسكندرية" },
    inclusions: { en: ["Guide", "All entry tickets", "Air-conditioned vehicle"], ar: ["مرشد", "كل تذاكر الدخول", "سيارة مكيفة"] },
    exclusions: { en: ["Lunch", "Gratuities"], ar: ["الغداء", "الإكراميات"] },
    whatToBring: { en: ["Walking shoes", "A windproof layer in winter"], ar: ["حذاء للمشي", "سترة تقي من الرياح في الشتاء"] },
    accessibility: { en: "The catacombs descend a spiral staircase with no lift. Everything else is largely step-free.", ar: "النزول إلى المقابر عبر سلم حلزوني ولا مصعد. أما بقية المواقع فتكاد تخلو من الدرج." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/alex-catacombs.webp", alt: { en: "Carved chamber in the catacombs", ar: "حجرة منحوتة في مقابر كوم الشقافة" } },
    gallery: [
      {
        src: "/images/experiences/alex-catacombs-01.webp",
        alt: { en: "Carved chambers inside the Kom El Shoqafa catacombs", ar: "حجرات منحوتة في الصخر داخل مقابر كوم الشقافة" },
      },
      {
        src: "/images/experiences/alex-catacombs-02.webp",
        alt: { en: "Pompey's Pillar above the Serapeum", ar: "عمود السواري فوق السيرابيوم" },
      },
    ],
    accent: "#2a719a",
  },
  {
    id: "exp-alex-seafood",
    slug: "alexandria-seafood-cooking-class",
    name: { en: "Mediterranean Seafood Class", ar: "درس طبخ مأكولات بحرية متوسطية" },
    destinationSlug: "alexandria",
    category: "food",
    travelStyles: ["family", "romantic"],
    environment: "indoor",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 240,
    priceFrom: 70,
    privateSupplement: 45,
    rating: 4.9,
    reviewCount: 96,
    maxGroupSize: 8,
    minAge: 10,
    summary: {
      en: "Buy the catch at the fish market, then cook it four ways in a family kitchen above the harbour.",
      ar: "اشترِ سمك اليوم من السوق، ثم اطبخه بأربع طرق في مطبخ عائلي يطل على الميناء.",
    },
    description: {
      en: "Start at the Anfoushi fish market choosing sea bass, calamari and shrimp with your host, who will explain how Alexandrians judge freshness. Cook singari-style baked fish, garlic shrimp, a tahini salad and rice with a sea-facing balcony, then eat what you made.",
      ar: "تبدأ في سوق سمك الأنفوشي باختيار القاروص والكاليماري والجمبري مع مضيفك، وهو يشرح لك كيف يعرف السكندريون السمك الطازج من غيره. ثم تطبخ سمكًا سنجاري في الفرن، وجمبريًا بالثوم، وسلطة طحينة، وأرزًا، في مطبخ شرفته على البحر، وتأكل ما طبخته بيدك.",
    },
    schedule: { en: "Tuesday, Thursday and Saturday, 11:00", ar: "الثلاثاء والخميس والسبت، 11:00" },
    meetingPoint: { en: "Anfoushi fish market entrance", ar: "مدخل سوق سمك الأنفوشي" },
    inclusions: { en: ["Market tour and all ingredients", "Cooking class with a local host", "The full meal you cook", "Recipe cards in English and Arabic"], ar: ["جولة في السوق وجميع المكونات", "درس طهي مع مضيف محلي", "الوجبة كاملة، من طبخك", "بطاقات وصفات بالعربية والإنجليزية"] },
    exclusions: { en: ["Transfers", "Alcoholic drinks"], ar: ["الانتقالات", "المشروبات الكحولية"] },
    whatToBring: { en: ["An appetite", "Shellfish allergies declared at booking"], ar: ["شهية مفتوحة", "إبلاغنا عند الحجز بأي حساسية من القشريات"] },
    accessibility: { en: "The kitchen is on the first floor and reached by stairs only.", ar: "المطبخ في الطابق الأول، والوصول إليه بالسلم فقط." },
    cancellation: { en: "Free cancellation up to 48 hours before", ar: "إلغاء مجاني حتى 48 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/alex-seafood.webp", alt: { en: "Choosing the catch at the fish market", ar: "اختيار السمك في السوق" } },
    gallery: [
      {
        src: "/images/experiences/alex-seafood-01.webp",
        alt: { en: "Grilled fish with the sides that come with it", ar: "سمك مشوي وما يُقدَّم معه" },
      },
      {
        src: "/images/experiences/alex-seafood-02.webp",
        alt: { en: "Fish over the coals at the market grill", ar: "السمك على الفحم في مشواة السوق" },
      },
    ],
    accent: "#2c6e67",
  },
  {
    id: "exp-luxor-balloon",
    slug: "luxor-hot-air-balloon",
    name: { en: "Hot Air Balloon over the Valley", ar: "منطاد فوق وادي الملوك" },
    destinationSlug: "luxor",
    category: "adventure",
    travelStyles: ["romantic", "luxury", "history"],
    environment: "outdoor",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 180,
    priceFrom: 125,
    privateSupplement: 480,
    rating: 4.9,
    reviewCount: 731,
    maxGroupSize: 20,
    minAge: 6,
    summary: {
      en: "Forty-five minutes over the Theban necropolis as the sun comes up behind Karnak.",
      ar: "45 دقيقة في الهواء فوق جبّانة طيبة، والشمس تطلع من خلف الكرنك.",
    },
    description: {
      en: "Cross the river in the dark, watch the envelopes inflate on the launch field, and lift off in time to see first light hit Hatshepsut's terraces. The flight drifts over the Valley of the Kings, the Colossi of Memnon and the green strip of farmland before setting down in a field.",
      ar: "تعبر النهر في العتمة، وتشاهد المناطيد تنتفخ في أرض الإقلاع، وترتفع في اللحظة المناسبة لترى أول شعاع يضرب مدرجات معبد حتشبسوت. ينساب المنطاد فوق وادي الملوك وتمثالي ممنون والشريط الأخضر من الحقول، ثم يحطّ في أحد الحقول.",
    },
    schedule: { en: "Daily at dawn, subject to wind", ar: "يوميًا مع الفجر، بحسب حالة الرياح" },
    meetingPoint: { en: "Hotel pickup, roughly 04:30 in winter", ar: "اصطحاب من الفندق، نحو 04:30 في الشتاء" },
    inclusions: { en: ["Transfers and river crossing", "45-minute flight", "Flight certificate", "Light breakfast"], ar: ["الانتقالات وعبور النهر", "تحليق لمدة 45 دقيقة", "شهادة تحليق", "فطور خفيف"] },
    exclusions: { en: ["Gratuity for the ground crew", "Hotel breakfast you will miss"], ar: ["إكرامية الطاقم الأرضي", "فطور الفندق، فستكون في الجو وقتها"] },
    whatToBring: { en: ["A warm layer for dawn", "Camera strap, not a loose phone"], ar: ["ملابس دافئة لبرد الفجر", "كاميرا بحزام، لا هاتفًا مرخيًا في اليد"] },
    accessibility: { en: "Boarding means climbing over the basket wall, roughly one metre high, unaided.", ar: "الصعود إلى السلة يعني تخطّي حافتها التي يبلغ ارتفاعها نحو متر، دون مساعدة." },
    cancellation: { en: "Full refund if cancelled for weather, which happens often and without warning", ar: "استرداد كامل إذا أُلغيت الرحلة بسبب الطقس، وهذا يحدث كثيرًا ومن دون سابق إنذار" },
    heroImage: { src: "/images/experiences/luxor-balloon.webp", alt: { en: "Balloons over the west bank at dawn", ar: "مناطيد فوق البر الغربي عند الفجر" } },
    gallery: [
      {
        src: "/images/experiences/luxor-balloon-01.webp",
        alt: { en: "Balloons over the farmland on the west bank", ar: "المناطيد فوق حقول البر الغربي" },
      },
      {
        src: "/images/experiences/luxor-balloon-02.webp",
        alt: { en: "A basket lifting into the first light", ar: "سلة ترتفع مع أول الضوء" },
      },
    ],
    accent: "#c85f26",
  },
  {
    id: "exp-valley-kings",
    slug: "valley-of-the-kings-private",
    name: { en: "Valley of the Kings, Privately", ar: "وادي الملوك في جولة خاصة" },
    destinationSlug: "luxor",
    category: "history",
    travelStyles: ["history", "luxury"],
    environment: "outdoor",
    groupFormat: ["private"],
    familyFriendly: true,
    durationMinutes: 300,
    priceFrom: 110,
    privateSupplement: 0,
    rating: 4.9,
    reviewCount: 289,
    maxGroupSize: 6,
    minAge: null,
    summary: {
      en: "Four tombs including Seti I, chosen for painting quality rather than fame, with an Egyptologist.",
      ar: "أربع مقابر بينها مقبرة سيتي الأول، اختيرت لجمال رسومها لا لشهرتها، مع مرشد متخصص في علم المصريات.",
    },
    description: {
      en: "Your guide picks the day's tombs based on which are open and least busy, then adds Seti I, the longest and most completely painted tomb in the valley. The morning finishes at Hatshepsut's terraces and Medinet Habu, where the original colour survives on the ceilings.",
      ar: "يختار مرشدك مقابر اليوم من بين المفتوح منها والأقل زحامًا، ويضيف إليها مقبرة سيتي الأول، أطول مقابر الوادي وأكملها رسومًا. ينتهي الصباح عند مدرجات معبد حتشبسوت ثم مدينة هابو، حيث ما زالت الألوان الأصلية باقية على الأسقف.",
    },
    schedule: { en: "Daily, 06:30 pickup", ar: "يوميًا، الاصطحاب من الفندق في 06:30" },
    meetingPoint: { en: "Hotel pickup, either bank", ar: "اصطحاب من فندقك على أي من الضفتين" },
    inclusions: { en: ["Private Egyptologist", "Valley entry with three tombs", "Seti I supplementary ticket", "Private vehicle and water"], ar: ["مرشد خاص متخصص في علم المصريات", "تذكرة الوادي وتشمل ثلاث مقابر", "التذكرة الإضافية لمقبرة سيتي الأول", "سيارة خاصة ومياه"] },
    exclusions: { en: ["Tutankhamun's tomb ticket", "Photography permit", "Lunch"], ar: ["تذكرة مقبرة توت عنخ آمون", "تصريح التصوير", "الغداء"] },
    whatToBring: { en: ["Hat, water, sunscreen", "Cash for the photo permit"], ar: ["قبعة وماء وواقٍ من الشمس", "نقود لتصريح التصوير"] },
    accessibility: { en: "A shuttle runs to the tomb entrances, but the tombs themselves are ramped or stepped descents with no handrails.", ar: "عربة كهربائية تنقلك إلى مداخل المقابر، لكن المقابر نفسها ممرات منحدرة أو درجات نازلة بلا درابزين." },
    cancellation: { en: "Free cancellation up to 48 hours before", ar: "إلغاء مجاني حتى 48 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/valley-kings.webp", alt: { en: "Painted tomb wall in the Valley of the Kings", ar: "رسوم على جدار مقبرة في وادي الملوك" } },
    gallery: [
      {
        src: "/images/experiences/valley-kings-01.webp",
        alt: { en: "Painted columns at Medinet Habu, where the morning ends", ar: "أعمدة مدينة هابو الملوّنة، حيث ينتهي الصباح" },
      },
      {
        src: "/images/experiences/valley-kings-02.webp",
        alt: { en: "The valley from above, tomb doors cut into the rock", ar: "الوادي من أعلى وأبواب المقابر منحوتة في الصخر" },
      },
    ],
    accent: "#a8853b",
  },
  {
    id: "exp-karnak-sound",
    slug: "karnak-sound-and-light",
    name: { en: "Karnak Sound and Light", ar: "عرض الصوت والضوء في الكرنك" },
    destinationSlug: "luxor",
    category: "culture",
    travelStyles: ["history", "family", "romantic"],
    environment: "outdoor",
    groupFormat: ["shared"],
    familyFriendly: true,
    durationMinutes: 90,
    priceFrom: 32,
    privateSupplement: 0,
    rating: 4.4,
    reviewCount: 143,
    maxGroupSize: 40,
    minAge: null,
    summary: {
      en: "The temple after closing, walked in the dark while it is lit hall by hall.",
      ar: "المعبد بعد إغلاق أبوابه، تمشي فيه في الظلام بينما تُضاء قاعاته واحدة تلو الأخرى.",
    },
    description: {
      en: "The audience moves through Karnak rather than sitting in front of it. The narration is theatrical and the history is broad-brush, but standing among 134 lit columns with the site otherwise empty is worth the ticket on its own.",
      ar: "هنا يتحرك الجمهور داخل الكرنك بدل أن يجلس أمامه. السرد مسرحي، والتاريخ فيه بخطوط عريضة، لكن أن تقف بين 134 عمودًا مضاءً والمعبد خالٍ إلا منك ومن مجموعتك يستحق ثمن التذكرة وحده.",
    },
    schedule: { en: "Nightly, in English or Arabic depending on the session", ar: "كل ليلة، بالإنجليزية أو بالعربية بحسب موعد العرض" },
    meetingPoint: { en: "Karnak Temple main gate", ar: "البوابة الرئيسية لمعبد الكرنك" },
    inclusions: { en: ["Show ticket", "Multilingual headset"], ar: ["تذكرة العرض", "سماعة بعدة لغات"] },
    exclusions: { en: ["Transfers", "Guide"], ar: ["الانتقالات", "المرشد"] },
    whatToBring: { en: ["Flat shoes for uneven stone", "A light jacket"], ar: ["حذاء مريح بنعل مسطح، فالأرض حجرية غير مستوية", "سترة خفيفة"] },
    accessibility: { en: "The route crosses uneven ancient paving in low light and is not suitable for wheelchairs.", ar: "يمر المسار فوق أرضية أثرية غير مستوية في إضاءة خافتة، ولا يناسب الكراسي المتحركة." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/karnak-night.webp", alt: { en: "The obelisk at Karnak in late light", ar: "مسلة الكرنك في ضوء آخر النهار" } },
    gallery: [
      {
        src: "/images/experiences/karnak-night-01.webp",
        alt: { en: "Columns of the Great Hypostyle Hall", ar: "أعمدة قاعة الأساطين الكبرى" },
      },
      {
        src: "/images/experiences/karnak-night-02.webp",
        alt: { en: "An obelisk standing above the ruins", ar: "مسلة قائمة فوق الأطلال" },
      },
    ],
    accent: "#8a3b17",
  },
  {
    id: "exp-abu-simbel",
    slug: "abu-simbel-sunrise",
    name: { en: "Abu Simbel at Sunrise", ar: "أبو سمبل عند الشروق" },
    destinationSlug: "aswan",
    category: "history",
    travelStyles: ["history", "luxury"],
    environment: "outdoor",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 600,
    priceFrom: 105,
    privateSupplement: 90,
    rating: 4.9,
    reviewCount: 466,
    maxGroupSize: 14,
    minAge: null,
    summary: {
      en: "Three hours south before dawn to reach the colossi in the first light, then back by afternoon.",
      ar: "ثلاث ساعات جنوبًا قبل الفجر لتصل إلى التماثيل مع أول الضوء، وتعود إلى أسوان بعد الظهر.",
    },
    description: {
      en: "Ramesses II cut four twenty-metre figures into a cliff, and in the 1960s the whole temple was sawn into blocks and lifted sixty metres to escape Lake Nasser. Arriving at opening means seeing the facade lit orange with almost nobody in the frame.",
      ar: "نحت رمسيس الثاني أربعة تماثيل لنفسه بارتفاع عشرين مترًا في واجهة الجبل، وفي الستينيات قُطع المعبد كله إلى كتل ورُفع ستين مترًا إلى أعلى هربًا من مياه بحيرة ناصر. الوصول مع فتح الأبواب يعني أن ترى الواجهة وقد اصطبغت بالبرتقالي، وليس في الصورة أحد تقريبًا.",
    },
    schedule: { en: "Daily, 04:00 departure by road", ar: "يوميًا، التحرك برًا في 04:00" },
    meetingPoint: { en: "Hotel pickup in Aswan", ar: "اصطحاب من فندقك في أسوان" },
    inclusions: { en: ["Air-conditioned road transfer", "Egyptologist guide", "Temple entry tickets", "Breakfast box"], ar: ["انتقال برًا بسيارة مكيّفة", "مرشد متخصص في علم المصريات", "تذاكر دخول المعبدين", "وجبة فطور جاهزة"] },
    exclusions: { en: ["Flight upgrade", "Lunch", "Gratuities"], ar: ["الذهاب بالطائرة بدل الطريق البري", "الغداء", "الإكراميات"] },
    whatToBring: { en: ["Passport for the checkpoint", "Sun protection", "Something to sleep on in the van"], ar: ["جواز السفر لنقطة التفتيش", "واقٍ من الشمس", "وسادة أو ما يعينك على النوم في السيارة"] },
    accessibility: { en: "Step-free from the car park to the temple terrace along a paved path.", ar: "ممر مرصوف بلا درج من موقف السيارات حتى ساحة المعبد." },
    cancellation: { en: "Free cancellation up to 48 hours before", ar: "إلغاء مجاني حتى 48 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/abu-simbel.webp", alt: { en: "The pillared hall of Nefertari's temple at Abu Simbel", ar: "بهو الأعمدة في معبد نفرتاري بأبو سمبل" } },
    gallery: [
      {
        src: "/images/experiences/abu-simbel-01.webp",
        alt: { en: "The small temple of Nefertari, cut into the cliff", ar: "معبد نفرتاري الصغير المنحوت في الصخر" },
      },
      {
        src: "/images/experiences/abu-simbel-02.webp",
        alt: { en: "Inside the great temple of Ramesses II", ar: "داخل المعبد الكبير لرمسيس الثاني" },
      },
    ],
    accent: "#c85f26",
  },
  {
    id: "exp-nubian-village",
    slug: "nubian-village-lunch",
    name: { en: "Nubian Village Lunch", ar: "غداء في قرية نوبية" },
    destinationSlug: "aswan",
    category: "culture",
    travelStyles: ["family", "romantic", "nature"],
    environment: "outdoor",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 240,
    priceFrom: 48,
    privateSupplement: 30,
    rating: 4.8,
    reviewCount: 205,
    maxGroupSize: 10,
    minAge: null,
    summary: {
      en: "A motorboat across to Gharb Soheil for a home-cooked meal in an indigo courtyard.",
      ar: "تعبر بقارب إلى غرب سهيل لتتغدى غداءً بيتيًا في فناء مصبوغ بالنيلي.",
    },
    description: {
      en: "The Nubian villages upstream of Aswan paint their houses in flat blocks of indigo, ochre and rose. Lunch is served in a family courtyard: slow-cooked tagine, fresh bread, hibiscus, and an hour of conversation about a culture displaced twice by dams.",
      ar: "تطلي القرى النوبية جنوب أسوان بيوتها بمساحات صريحة من النيلي والأصفر الترابي والوردي. يُقدَّم الغداء في فناء بيت العائلة: طاجن مطهو على مهل، وخبز طازج، وكركديه، وساعة من الحديث عن شعب هُجِّر مرتين بسبب السدود.",
    },
    schedule: { en: "Daily, 11:00", ar: "يوميًا، 11:00" },
    meetingPoint: { en: "Aswan public boat landing", ar: "مرسى القوارب العام في أسوان" },
    inclusions: { en: ["Return motorboat", "Home-cooked lunch", "Village host and guide", "Hibiscus and tea"], ar: ["قارب بمحرك ذهابًا وإيابًا", "غداء بيتي", "مضيف ومرشد من القرية", "كركديه وشاي"] },
    exclusions: { en: ["Camel ride option", "Souvenirs"], ar: ["ركوب الجمل (اختياري)", "الهدايا التذكارية"] },
    whatToBring: { en: ["Modest clothing", "Cash for handicrafts"], ar: ["ملابس محتشمة", "نقود للمشغولات اليدوية"] },
    accessibility: { en: "Boarding is from a low jetty and the village lanes are sand. Assistance can be arranged on request.", ar: "الركوب من رصيف منخفض، وطرقات القرية رملية. نرتّب المساعدة إن طلبتها." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/nubian-village.webp", alt: { en: "Painted Nubian houses above the Nile", ar: "بيوت نوبية ملونة فوق النيل" } },
    gallery: [
      {
        src: "/images/experiences/nubian-village-01.webp",
        alt: { en: "Domed Nubian houses above the water", ar: "بيوت نوبية مقبّبة فوق الماء" },
      },
      {
        src: "/images/experiences/nubian-village-02.webp",
        alt: { en: "Cones of spice in the village market", ar: "أكوام البهارات المخروطية في سوق القرية" },
      },
    ],
    accent: "#2a719a",
  },
  {
    id: "exp-felucca-sunset",
    slug: "felucca-sunset-sail",
    name: { en: "Felucca Sunset Sail", ar: "جولة بالفلوكة عند الغروب" },
    destinationSlug: "aswan",
    category: "nature",
    travelStyles: ["romantic", "family", "nature"],
    environment: "water",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 120,
    priceFrom: 26,
    privateSupplement: 35,
    rating: 4.9,
    reviewCount: 612,
    maxGroupSize: 8,
    minAge: null,
    summary: {
      en: "Two hours under sail around Elephantine and Kitchener's Island, engine off the whole way.",
      ar: "ساعتان بالشراع وحده حول جزيرة إلفنتين وجزيرة النباتات، من دون محرك على الإطلاق.",
    },
    description: {
      en: "Feluccas have not changed design in centuries and they still do the job better than anything with a motor. The route curls between granite boulders, past the Aga Khan mausoleum on the west bank, and holds still in the middle of the river while the sun goes down.",
      ar: "لم يتغير تصميم الفلوكة منذ قرون، وما زالت تؤدي المهمة أفضل من أي مركب بمحرك. يلتف المسار بين صخور الجرانيت، ويمر بضريح الأغا خان على البر الغربي، ثم يتوقف في منتصف النهر ريثما تغيب الشمس.",
    },
    schedule: { en: "Daily, departing 90 minutes before sunset", ar: "يوميًا، الإبحار قبل الغروب بساعة ونصف" },
    meetingPoint: { en: "Corniche felucca mooring, Aswan", ar: "مرسى الفلايك على كورنيش أسوان" },
    inclusions: { en: ["Private or shared felucca with captain", "Hibiscus and water", "Two-hour sail"], ar: ["فلوكة خاصة أو مشتركة مع ربانها", "كركديه وماء", "ساعتان من الإبحار"] },
    exclusions: { en: ["Island entry tickets", "Dinner"], ar: ["تذاكر دخول الجزر", "العشاء"] },
    whatToBring: { en: ["A layer for after sunset", "Cash for the captain's tip"], ar: ["سترة خفيفة لما بعد الغروب", "نقود لإكرامية الربان"] },
    accessibility: { en: "Boarding is a step down into a low open boat with no rail.", ar: "الركوب بخطوة نزول إلى مركب مفتوح منخفض بلا حاجز." },
    cancellation: { en: "Free cancellation up to 12 hours before", ar: "إلغاء مجاني حتى 12 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/felucca.webp", alt: { en: "Feluccas under sail on the Nile", ar: "فلايك تبحر في النيل" } },
    gallery: [
      {
        src: "/images/experiences/felucca-01.webp",
        alt: { en: "A felucca under full sail off Aswan", ar: "فلوكة بشراع مفرود قبالة أسوان" },
      },
      {
        src: "/images/experiences/felucca-02.webp",
        alt: { en: "Still water and a single sail", ar: "ماء ساكن وشراع وحيد" },
      },
    ],
    accent: "#2c6e67",
  },
  {
    id: "exp-nile-cruise",
    slug: "nile-cruise-aswan-to-luxor",
    name: { en: "Nile Cruise, Aswan to Luxor", ar: "رحلة نيلية من أسوان إلى الأقصر" },
    destinationSlug: "aswan",
    category: "water",
    travelStyles: ["luxury", "romantic", "history"],
    environment: "water",
    // A sixty-berth vessel is not chartered by the cabin; the cruise is shared.
    groupFormat: ["shared"],
    familyFriendly: true,
    // Four days and three nights: the last morning is a day of the trip.
    durationMinutes: 5760,
    priceFrom: 590,
    privateSupplement: 0,
    rating: 4.8,
    reviewCount: 388,
    maxGroupSize: 60,
    minAge: null,
    summary: {
      en: "Three nights downstream with Kom Ombo and Edfu on the way, all meals aboard.",
      ar: "ثلاث ليالٍ مع مجرى النهر، تتوقف في كوم أمبو وإدفو، وكل الوجبات على المركب.",
    },
    description: {
      en: "The classic river route, and still the most comfortable way to see the temples between the two cities. Kom Ombo is visited at dusk when the light is best, Edfu by horse carriage in the early morning, and the rest of the time the valley simply moves past the sun deck.",
      ar: "الطريق النهري الكلاسيكي، وما زال أريح وسيلة لرؤية المعابد الواقعة بين المدينتين. تزور كوم أمبو عند الغسق حين يكون الضوء في أجمل حالاته، وإدفو بعربة الحنطور في الصباح الباكر، وفي بقية الوقت يمر الوادي أمامك وأنت على سطح المركب.",
    },
    schedule: { en: "Departures on set days; four days and three nights", ar: "الإبحار في أيام محددة، أربعة أيام وثلاث ليالٍ" },
    meetingPoint: { en: "Cruise mooring, Aswan corniche", ar: "مرسى الرحلات النيلية، كورنيش أسوان" },
    inclusions: { en: ["Three nights aboard in an outside cabin", "Full board", "Guided temple visits at Kom Ombo and Edfu", "Onboard Egyptologist"], ar: ["ثلاث ليالٍ في كابينة بنافذة خارجية", "إقامة كاملة بكل الوجبات", "زيارة معبدي كوم أمبو وإدفو مع مرشد", "مرشد متخصص في علم المصريات على المركب"] },
    exclusions: { en: ["Drinks", "Optional excursions", "Gratuities for the crew"], ar: ["المشروبات", "الرحلات الاختيارية", "إكراميات الطاقم"] },
    whatToBring: { en: ["A soft bag rather than a hard case", "Smart casual for dinner"], ar: ["حقيبة قماش لا حقيبة صلبة", "ملابس أنيقة للعشاء"] },
    accessibility: { en: "Most vessels have no lift between decks and cabin doorways are narrow.", ar: "معظم المراكب بلا مصعد بين الطوابق، وأبواب الكبائن ضيقة." },
    cancellation: { en: "Free cancellation up to 14 days before", ar: "إلغاء مجاني حتى 14 يومًا قبل الموعد" },
    heroImage: { src: "/images/experiences/nile-cruise.webp", alt: { en: "A river cruiser moored on the Nile", ar: "باخرة نيلية راسية على الضفة" } },
    gallery: [
      {
        src: "/images/experiences/nile-cruise-01.webp",
        alt: { en: "A cruise boat against the desert bank", ar: "باخرة نيلية أمام الضفة الصحراوية" },
      },
      {
        src: "/images/experiences/nile-cruise-02.webp",
        alt: { en: "The portal at Kom Ombo, the stop at dusk", ar: "بوابة كوم أمبو، محطة الغسق" },
      },
    ],
    accent: "#1f5a7d",
  },
  {
    id: "exp-sand-sea",
    slug: "great-sand-sea-safari",
    name: { en: "Great Sand Sea Safari", ar: "سفاري بحر الرمال الأعظم" },
    destinationSlug: "siwa-oasis",
    category: "adventure",
    travelStyles: ["desert", "nature"],
    environment: "desert",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 330,
    priceFrom: 68,
    privateSupplement: 55,
    rating: 4.9,
    reviewCount: 241,
    maxGroupSize: 6,
    minAge: 8,
    summary: {
      en: "Dune driving, sandboarding, a fossil field and a hot spring, ending with sunset on a high ridge.",
      ar: "قيادة بين الكثبان، وتزلج على الرمال، وحقل أحافير، وعين ساخنة، والختام غروب من فوق كثيب عالٍ.",
    },
    description: {
      en: "A licensed Siwan driver takes a 4x4 into the dune field west of the oasis. You sandboard a few slopes, walk a bed of marine fossils that were a seabed forty million years ago, swim in a hot spring at Bir Wahed, and watch the sun go down from the top of a dune with tea brewing on a fire.",
      ar: "سائق سيوي مرخّص يأخذك بسيارة دفع رباعي إلى بحر الرمال غرب الواحة. تتزلج على بعض المنحدرات، وتمشي فوق طبقة من أحافير بحرية كانت قاع بحر قبل أربعين مليون سنة، وتسبح في عين ساخنة في بئر واحد، وتشاهد غروب الشمس من قمة كثيب والشاي يغلي على النار.",
    },
    schedule: { en: "Daily, 14:00 departure", ar: "يوميًا، التحرك في 14:00" },
    meetingPoint: { en: "Your Siwa lodge or the town square", ar: "من نُزُلك في سيوة أو من ميدان البلدة" },
    inclusions: { en: ["Licensed 4x4 and desert driver", "Sandboard hire", "Hot spring stop", "Bedouin tea at sunset"], ar: ["سيارة دفع رباعي مرخّصة مع سائق صحراوي", "إيجار لوح التزلج على الرمال", "توقف عند العين الساخنة", "شاي بدوي عند الغروب"] },
    exclusions: { en: ["Dinner", "Towels", "Overnight camping upgrade"], ar: ["العشاء", "المناشف", "المبيت في الصحراء (بتكلفة إضافية)"] },
    whatToBring: { en: ["Swimwear worn under clothing", "A towel", "Something to keep sand out of a camera"], ar: ["ملابس سباحة تلبسها تحت ثيابك", "منشفة", "غطاء يحمي الكاميرا من الرمل"] },
    accessibility: { en: "Repeated steep dune descents in a vehicle. Not advisable with back or neck injuries or during pregnancy.", ar: "السيارة تهبط كثبانًا شديدة الانحدار مرارًا. لا ننصح بها لمن يعاني إصابة في الظهر أو الرقبة، ولا للحوامل." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/sand-sea.webp", alt: { en: "Walking a dune crest at sunset", ar: "سير على قمة كثيب عند الغروب" } },
    gallery: [
      {
        src: "/images/experiences/sand-sea-01.webp",
        alt: { en: "A dune face with vehicles for scale", ar: "واجهة كثيب، والسيارات أسفله تُظهر ضخامته" },
      },
      {
        src: "/images/experiences/sand-sea-02.webp",
        alt: { en: "Low light along a dune ridge at the end of the day", ar: "ضوء خافت على حافة كثيب في آخر النهار" },
      },
    ],
    accent: "#9a7a54",
  },
  {
    id: "exp-siwa-salt",
    slug: "siwa-salt-lake-float",
    name: { en: "Salt Lake Float and Olive Grove Lunch", ar: "طفو في البحيرة الملحية وغداء في بستان زيتون" },
    destinationSlug: "siwa-oasis",
    category: "wellness",
    travelStyles: ["nature", "romantic"],
    environment: "outdoor",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 240,
    priceFrom: 42,
    privateSupplement: 28,
    rating: 4.8,
    reviewCount: 134,
    maxGroupSize: 10,
    minAge: null,
    summary: {
      en: "Float in water so saline you cannot sink, then eat under olive trees at the edge of the oasis.",
      ar: "اطفُ فوق ماء من شدة ملوحته لا يمكنك الغرق فيه، ثم تغدَّ تحت أشجار الزيتون على طرف الواحة.",
    },
    description: {
      en: "Siwa's salt pools are old quarry basins with crystalline white edges and water more buoyant than the Dead Sea. The float lasts about twenty minutes before the salt asks you to rinse. Lunch afterwards is olives, dates, flatbread and slow-roasted vegetables in a grove.",
      ar: "برك الملح في سيوة أحواض محاجر قديمة تحيط بها حواف بلورية بيضاء، وماؤها يرفعك أكثر مما يرفعك البحر الميت. يدوم الطفو نحو عشرين دقيقة قبل أن يلحّ عليك الملح بالشطف. ثم غداء في بستان: زيتون وتمر وخبز بلدي وخضار مشوي على نار هادئة.",
    },
    schedule: { en: "Daily, 10:00", ar: "يوميًا، 10:00" },
    meetingPoint: { en: "Your Siwa lodge", ar: "من نُزُلك في سيوة" },
    inclusions: { en: ["Transfers within the oasis", "Salt lake access", "Fresh-water rinse", "Grove lunch"], ar: ["الانتقالات داخل الواحة", "دخول البحيرة الملحية", "شطف بالماء العذب", "غداء في البستان"] },
    exclusions: { en: ["Towels", "Massage add-on"], ar: ["المناشف", "جلسة تدليك (بتكلفة إضافية)"] },
    whatToBring: { en: ["Swimwear you do not mind bleaching", "Sandals", "No fresh shaving cuts"], ar: ["ملابس سباحة لا يهمك إن بهت لونها", "صندل", "بشرة بلا جروح حلاقة حديثة، فالملح يلسع"] },
    accessibility: { en: "The pool edge is uneven crystallised salt, sharp in places, with no handrail.", ar: "حافة البركة من الملح المتبلور، غير مستوية وحادة في مواضع، ولا درابزين." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/siwa-salt.webp", alt: { en: "A turquoise salt pool with white banks", ar: "بركة ملحية فيروزية بضفاف بيضاء" } },
    gallery: [
      {
        src: "/images/experiences/siwa-salt-01.webp",
        alt: { en: "A salt pool ringed with white crystal", ar: "بركة ملحية تحيط بها بلورات بيضاء" },
      },
      {
        src: "/images/experiences/siwa-salt-02.webp",
        alt: { en: "Midday sun on the salt water", ar: "شمس الظهيرة على الماء المالح" },
      },
    ],
    accent: "#468a82",
  },
  {
    id: "exp-siwa-bike",
    slug: "siwa-oracle-bike-tour",
    name: { en: "Oracle and Olive Groves by Bicycle", ar: "معبد التنبؤات والبساتين بالدراجة" },
    destinationSlug: "siwa-oasis",
    category: "nature",
    travelStyles: ["nature", "history", "family"],
    environment: "outdoor",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 210,
    priceFrom: 30,
    privateSupplement: 22,
    rating: 4.7,
    reviewCount: 88,
    maxGroupSize: 8,
    minAge: 12,
    summary: {
      en: "Flat lanes between palm gardens to the Temple of the Oracle and Cleopatra's Spring.",
      ar: "دروب مستوية بين حدائق النخيل حتى معبد التنبؤات وعين كليوباترا.",
    },
    description: {
      en: "Siwa is best seen from a bicycle: the oasis is flat, the lanes are shaded, and nothing worth reaching is more than four kilometres away. The route takes in the oracle where Alexander was told he was divine, the ruins at Umm Ubayda, and a spring stop before returning through the groves.",
      ar: "أجمل ما تُرى سيوة من فوق دراجة: الواحة مستوية، والدروب مظللة، وكل ما يستحق الزيارة على بعد أربعة كيلومترات على الأكثر. يمر المسار بمعبد التنبؤات حيث قيل للإسكندر إنه إله، وأطلال أم عبيدة، ووقفة عند عين ماء قبل العودة عبر البساتين.",
    },
    schedule: { en: "Daily, 09:00 and 15:30", ar: "يوميًا، 09:00 و15:30" },
    meetingPoint: { en: "Siwa town square bicycle stand", ar: "موقف الدراجات في ميدان سيوة" },
    inclusions: { en: ["Bicycle hire", "Local guide", "Temple entry", "Water"], ar: ["إيجار الدراجة", "مرشد محلي", "دخول المعبد", "ماء"] },
    exclusions: { en: ["Helmets, which are not stocked locally", "Spring entry donation"], ar: ["الخوذة، ولا تتوفر في سيوة", "تبرع رمزي عند العين"] },
    whatToBring: { en: ["Sun hat", "Modest clothing for the village lanes"], ar: ["قبعة شمس", "ملابس محتشمة لدروب القرية"] },
    accessibility: { en: "Requires confident cycling on unpaved lanes. A car alternative is available for the same route.", ar: "يحتاج إلى من يجيد ركوب الدراجة على دروب ترابية. ويمكن قطع المسار نفسه بالسيارة لمن يفضّل." },
    cancellation: { en: "Free cancellation up to 12 hours before", ar: "إلغاء مجاني حتى 12 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/siwa-bike.webp", alt: { en: "The ruins at Aghurmi beside the Temple of the Oracle", ar: "أطلال أغورمي بجوار معبد التنبؤات" } },
    gallery: [
      {
        src: "/images/experiences/siwa-bike-01.webp",
        alt: { en: "What remains of the Temple of the Oracle", ar: "ما تبقى من معبد التنبؤات" },
      },
      {
        src: "/images/experiences/siwa-bike-02.webp",
        alt: { en: "The mudbrick roofs of Shali", ar: "أسطح شالي المبنية من الطوب اللبن" },
      },
    ],
    accent: "#2c6e67",
  },
  {
    id: "exp-white-desert-camp",
    slug: "white-desert-overnight-camp",
    name: { en: "White Desert Overnight Camp", ar: "ليلة في مخيم بالصحراء البيضاء" },
    destinationSlug: "white-desert",
    category: "adventure",
    travelStyles: ["desert", "nature", "romantic"],
    environment: "desert",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    // 13:00 from Bahariya to the morning after sunrise, back at Bawiti.
    durationMinutes: 1260,
    priceFrom: 180,
    privateSupplement: 140,
    rating: 4.9,
    reviewCount: 176,
    maxGroupSize: 8,
    minAge: 8,
    summary: {
      en: "Sleep among the chalk formations with no light pollution for two hundred kilometres.",
      ar: "تنام بين التكوينات الطباشيرية، وأقرب ضوء صناعي على بعد مئتي كيلومتر.",
    },
    description: {
      en: "Drive out from Bahariya through the Black Desert and Crystal Mountain, then set camp among the white formations in time for sunset. Dinner is cooked over a fire, the sky is as good as any on earth, and desert foxes usually turn up. You wake for first light on the chalk before driving back.",
      ar: "تنطلق من الواحات البحرية عبر الصحراء السوداء وجبل الكريستال، وتنصب المخيم بين التكوينات البيضاء قبل الغروب. العشاء يُطهى على النار، والسماء هنا لا تقل عن أي سماء على وجه الأرض، وثعالب الصحراء تزور المخيم في الغالب. تصحو مع أول الضوء على الطباشير ثم تعود.",
    },
    schedule: { en: "Daily departures from Bahariya, 13:00", ar: "يوميًا من الواحات البحرية، التحرك في 13:00" },
    meetingPoint: { en: "Bahariya Oasis, Bawiti village", ar: "الواحات البحرية، قرية الباويطي" },
    inclusions: { en: ["4x4 and desert guide", "Camping equipment and bedding", "Dinner and breakfast", "National park permit"], ar: ["سيارة دفع رباعي ومرشد صحراوي", "معدات التخييم والأغطية", "العشاء والفطور", "تصريح دخول المحمية"] },
    exclusions: { en: ["Transfer from Cairo", "Alcohol, which is not permitted in the park", "Showers"], ar: ["الانتقال من القاهرة", "الكحول، فهو ممنوع داخل المحمية", "دُش أو حمّام"] },
    whatToBring: { en: ["A warm layer, genuinely", "Head torch", "Wet wipes and your own rubbish bag"], ar: ["ملابس دافئة، ونحن جادون في هذا", "كشاف رأس", "مناديل مبللة وكيس تحمل فيه قمامتك"] },
    accessibility: { en: "Camping on sand with a shared tent and a desert toilet. No running water and no step-free facilities.", ar: "تخييم على الرمل في خيمة مشتركة، ودورة مياه صحراوية. لا ماء جارٍ، ولا مرافق مهيأة للكراسي المتحركة." },
    cancellation: { en: "Free cancellation up to 72 hours before", ar: "إلغاء مجاني حتى 72 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/white-desert-camp.webp", alt: { en: "Chalk pillars in the White Desert", ar: "أعمدة طباشيرية في الصحراء البيضاء" } },
    gallery: [
      {
        src: "/images/experiences/white-desert-camp-01.webp",
        alt: { en: "Camels resting where the camp is set", ar: "الجمال تستريح حيث يُنصب المخيم" },
      },
      {
        src: "/images/experiences/white-desert-camp-02.webp",
        alt: { en: "Chalk weathered into a mushroom", ar: "صخرة طباشيرية نحتتها الرياح على شكل فطر" },
      },
    ],
    accent: "#7c6144",
  },
  {
    id: "exp-giftun",
    slug: "giftun-island-snorkel-day",
    name: { en: "Giftun Island Snorkel Day", ar: "يوم غطس سطحي في جزيرة الجفتون" },
    destinationSlug: "hurghada",
    category: "water",
    travelStyles: ["beach", "family", "nature"],
    environment: "water",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 480,
    priceFrom: 46,
    privateSupplement: 260,
    rating: 4.7,
    reviewCount: 934,
    maxGroupSize: 25,
    minAge: null,
    summary: {
      en: "Two reef stops and a sandbank beach, with lunch cooked on the boat.",
      ar: "وقفتان عند الشعاب وشاطئ على لسان رملي، والغداء يُطهى على المركب.",
    },
    description: {
      en: "The standard Red Sea day out, done properly: a wooden boat rather than a crowded catamaran, two anchorages chosen for coral health rather than convenience, and a stop at the protected sandbank on Giftun's north shore. Guides stay in the water with weaker swimmers.",
      ar: "رحلة البحر الأحمر التقليدية، لكن على أصولها: مركب خشبي بدل الكاتاماران المكدّس، ومرسيان اختيرا لصحة الشعاب لا لقربهما، ووقفة عند اللسان الرملي المحمي على الشاطئ الشمالي للجفتون. المرشدون ينزلون الماء ويبقون مع من لا يجيد السباحة جيدًا.",
    },
    schedule: { en: "Daily, 08:00 to 16:00", ar: "يوميًا، من 08:00 إلى 16:00" },
    meetingPoint: { en: "Hurghada marina, or hotel pickup", ar: "مارينا الغردقة، أو اصطحاب من الفندق" },
    inclusions: { en: ["Boat with shade and toilets", "Mask, snorkel and fins", "Lunch and soft drinks", "Marine park fee"], ar: ["مركب مظلل وبه دورات مياه", "نظارة غطس وأنبوب تنفس وزعانف", "الغداء والمشروبات الغازية", "رسوم المحمية البحرية"] },
    exclusions: { en: ["Wetsuit hire in winter", "Diving supplement", "Gratuities"], ar: ["إيجار بدلة الغطس في الشتاء", "الغوص بالأسطوانات (بتكلفة إضافية)", "الإكراميات"] },
    whatToBring: { en: ["Reef-safe sunscreen only", "A towel", "A dry bag for your phone"], ar: ["واقي شمس لا يضر الشعاب المرجانية، ولا غيره", "منشفة", "كيس مقاوم للماء للهاتف"] },
    accessibility: { en: "Entry to the water is by ladder from the stern. Crew assistance is available.", ar: "النزول إلى الماء بسلّم من مؤخرة المركب، والطاقم جاهز للمساعدة." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/giftun.webp", alt: { en: "A boat pulled up on the white sand of Giftun Island", ar: "مركب راسٍ على رمال جزيرة الجفتون البيضاء" } },
    gallery: [
      {
        src: "/images/experiences/giftun-01.webp",
        alt: { en: "The reef and the sandbank from the air", ar: "الشعاب واللسان الرملي من الجو" },
      },
      {
        src: "/images/experiences/giftun-02.webp",
        alt: { en: "Angelfish over the coral in the shallows", ar: "أسماك ملائكية فوق المرجان في المياه الضحلة" },
      },
    ],
    accent: "#2a719a",
  },
  {
    id: "exp-eastern-desert-quad",
    slug: "eastern-desert-quad-and-bedouin-dinner",
    name: { en: "Eastern Desert Quad and Bedouin Dinner", ar: "دراجات رباعية في الصحراء الشرقية وعشاء بدوي" },
    destinationSlug: "hurghada",
    category: "adventure",
    travelStyles: ["desert", "family"],
    environment: "desert",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 300,
    priceFrom: 38,
    privateSupplement: 40,
    rating: 4.5,
    reviewCount: 617,
    maxGroupSize: 20,
    minAge: 6,
    summary: {
      en: "An hour on the quads into the hills, then dinner and stargazing at a Bedouin settlement.",
      ar: "ساعة بالدراجة الرباعية بين التلال، ثم عشاء ومراقبة للنجوم عند البدو.",
    },
    description: {
      en: "The Eastern Desert starts thirty minutes inland and the change is total: no sea, no resorts, just gravel plains and mountains. After the ride there is tea in a Bedouin camp, grilled dinner, a short camel ride for anyone who wants one, and a telescope out once the sky darkens.",
      ar: "تبدأ الصحراء الشرقية بعد نصف ساعة من الساحل، والتحول تام: لا بحر ولا منتجعات، بل سهول من الحصى وجبال. بعد الجولة شاي في مخيم بدوي، وعشاء مشاوي، وجولة قصيرة على الجمل لمن أراد، وتلسكوب يُخرج حين تظلم السماء.",
    },
    schedule: { en: "Daily, 15:00", ar: "يوميًا، 15:00" },
    meetingPoint: { en: "Hotel pickup in Hurghada", ar: "اصطحاب من فندقك في الغردقة" },
    inclusions: { en: ["Quad bike and helmet", "Bedouin camp dinner", "Camel ride", "Stargazing with a telescope"], ar: ["دراجة رباعية وخوذة", "عشاء في المخيم البدوي", "ركوب جمل", "مراقبة النجوم بالتلسكوب"] },
    exclusions: { en: ["Goggles, recommended and sold on site", "Drinks beyond tea and water"], ar: ["نظارة واقية، ننصح بها وتُباع في المكان", "أي مشروبات غير الشاي والماء"] },
    whatToBring: { en: ["Clothes you do not mind covering in dust", "A scarf for your face"], ar: ["ملابس لا يهمك أن يغطيها الغبار", "وشاح تلف به وجهك"] },
    accessibility: { en: "Riders must operate the quad themselves. Children ride as passengers with an adult.", ar: "كل مشارك يقود دراجته بنفسه، ويركب الأطفال خلف شخص بالغ." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/quad-desert.webp", alt: { en: "Quad bikes crossing a desert plain", ar: "دراجات رباعية تعبر سهلًا صحراويًا" } },
    gallery: [
      {
        src: "/images/experiences/quad-desert-01.webp",
        alt: { en: "Tracks carved across the sand by the ride out", ar: "آثار العجلات محفورة في الرمل على طول المسار" },
      },
      {
        src: "/images/experiences/quad-desert-02.webp",
        alt: { en: "The Eastern Desert mountains where the ride ends for dinner", ar: "جبال الصحراء الشرقية حيث تنتهي الجولة بالعشاء" },
      },
    ],
    accent: "#a94a1b",
  },
  {
    id: "exp-ras-mohammed",
    slug: "ras-mohammed-diving-day",
    name: { en: "Ras Mohammed Diving Day", ar: "يوم غوص في رأس محمد" },
    destinationSlug: "sharm-el-sheikh",
    category: "water",
    travelStyles: ["nature", "beach"],
    environment: "water",
    groupFormat: ["shared", "private"],
    familyFriendly: false,
    durationMinutes: 480,
    priceFrom: 115,
    privateSupplement: 180,
    rating: 4.9,
    reviewCount: 528,
    maxGroupSize: 12,
    minAge: 12,
    summary: {
      en: "Two guided dives at Shark and Yolanda reefs, where the wall drops into open blue.",
      ar: "غوصتان مع مرشد في شعبتي شارك ويولاندا، حيث يهوي الجدار المرجاني في الزرقة المفتوحة.",
    },
    description: {
      en: "Egypt's first national park and still its best diving. Shark Reef and Yolanda Reef sit side by side, the first a sheer wall with schooling barracuda and the second scattered with the cargo of a wreck that slid off the plateau in 1980. Two dives, full guiding, one boat day.",
      ar: "أول محمية طبيعية في مصر، وما زالت أفضل مواقع الغوص فيها. شعبة شارك وشعبة يولاندا متجاورتان: الأولى جدار عمودي تدور حوله أسراب الباراكودا، والثانية تتناثر فوقها حمولة سفينة انزلقت عن الهضبة عام 1980. غوصتان، وإرشاد كامل، ويوم واحد على المركب.",
    },
    schedule: { en: "Daily, 07:30 to 15:30", ar: "يوميًا، من 07:30 إلى 15:30" },
    meetingPoint: { en: "Travco or Naama Bay jetty", ar: "رصيف ترافكو أو خليج نعمة" },
    inclusions: { en: ["Two guided dives with tanks and weights", "Boat, lunch and drinks", "Marine park fees", "Divemaster in the water"], ar: ["غوصتان مع مرشد، بالأسطوانات والأثقال", "المركب والغداء والمشروبات", "رسوم المحمية البحرية", "مرشد غوص (دايف ماستر) معك في الماء"] },
    exclusions: { en: ["Full equipment hire", "Nitrox", "Insurance"], ar: ["إيجار طقم المعدات الكامل", "النيتروكس", "التأمين"] },
    whatToBring: { en: ["Certification card and logbook", "Reef-safe sunscreen", "Seasickness tablets if you need them"], ar: ["بطاقة الرخصة وسجل الغوصات", "واقي شمس آمن للشعاب", "أقراص دوار البحر إن كنت ممن يصيبهم"] },
    accessibility: { en: "Open Water certification or above is required. Entry is a giant stride from the platform.", ar: "يلزم رخصة المياه المفتوحة (Open Water) أو أعلى. النزول إلى الماء بخطوة واسعة من المنصة." },
    cancellation: { en: "Free cancellation up to 48 hours before", ar: "إلغاء مجاني حتى 48 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/ras-mohammed.webp", alt: { en: "The reef at Ras Mohammed from the surface", ar: "شعاب رأس محمد من سطح الماء" } },
    gallery: [
      {
        src: "/images/experiences/ras-mohammed-01.webp",
        alt: { en: "A sea fan on the wall at Ras Mohammed", ar: "مروحة بحرية على جدار رأس محمد" },
      },
      {
        src: "/images/experiences/ras-mohammed-02.webp",
        alt: { en: "Reef fish over hard coral", ar: "أسماك الشعاب فوق المرجان الصلب" },
      },
    ],
    accent: "#1f5a7d",
  },
  {
    id: "exp-thistlegorm",
    slug: "thistlegorm-wreck-dive",
    name: { en: "SS Thistlegorm Wreck Dive", ar: "غوص في حطام ثيستلجورم" },
    destinationSlug: "sharm-el-sheikh",
    category: "adventure",
    travelStyles: ["nature"],
    environment: "water",
    groupFormat: ["shared"],
    familyFriendly: false,
    durationMinutes: 720,
    priceFrom: 165,
    privateSupplement: 0,
    rating: 4.9,
    reviewCount: 302,
    maxGroupSize: 12,
    minAge: 18,
    summary: {
      en: "A long day out to the 1941 wreck still holding motorcycles, rifles and trucks in its holds.",
      ar: "يوم طويل في البحر حتى حطام سفينة غرقت عام 1941، وما زالت عنابرها مليئة بالدراجات النارية والبنادق والشاحنات.",
    },
    description: {
      en: "The Thistlegorm was bombed at anchor in October 1941 and settled upright in thirty metres, cargo intact. Two dives cover the exterior and then the holds, where Norton motorcycles are still strapped to Bedford trucks. Advanced certification and a minimum of twenty logged dives.",
      ar: "قُصفت ثيستلجورم وهي راسية في أكتوبر 1941 واستقرت واقفة على قاعدتها على عمق ثلاثين مترًا وحمولتها كما هي. تغطي الغوصة الأولى الهيكل من الخارج، والثانية العنابر حيث ما زالت دراجات نورتون مربوطة فوق شاحنات بيدفورد. يلزم رخصة متقدمة وعشرون غوصة مسجلة على الأقل.",
    },
    schedule: { en: "Set days, departing 04:45", ar: "أيام محددة، التحرك في 04:45" },
    meetingPoint: { en: "Sharm marina, dive centre desk", ar: "مارينا شرم، مكتب مركز الغوص" },
    inclusions: { en: ["Two guided wreck dives", "Tanks, weights and boat", "Breakfast and lunch aboard", "Torch hire"], ar: ["غوصتان في الحطام مع مرشد", "الأسطوانات والأثقال والمركب", "الفطور والغداء على المتن", "كشاف غوص"] },
    exclusions: { en: ["Nitrox", "Full equipment hire", "Dive insurance, which is mandatory"], ar: ["النيتروكس", "إيجار طقم المعدات الكامل", "تأمين الغوص، وهو إلزامي"] },
    whatToBring: { en: ["Logbook showing 20+ dives", "Advanced Open Water card", "Warm layers for the boat"], ar: ["سجل غوص يثبت عشرين غوصة فأكثر", "رخصة المياه المفتوحة المتقدمة", "ملابس دافئة للمركب"] },
    accessibility: { en: "Three hours each way in open water with strong currents on site. Not a beginner dive.", ar: "ثلاث ساعات ذهابًا ومثلها إيابًا في عرض البحر، والتيارات في الموقع قوية. ليست غوصة للمبتدئين." },
    cancellation: { en: "Free cancellation up to 72 hours before", ar: "إلغاء مجاني حتى 72 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/thistlegorm.webp", alt: { en: "Vehicles in the hold of the Thistlegorm", ar: "مركبات داخل عنبر ثيستلجورم" } },
    gallery: [
      {
        src: "/images/experiences/thistlegorm-01.webp",
        alt: { en: "A locomotive on the Thistlegorm's deck", ar: "قاطرة على سطح ثيستلجورم" },
      },
      {
        src: "/images/experiences/thistlegorm-02.webp",
        alt: { en: "The Thistlegorm's holds, still loaded", ar: "عنابر ثيستلجورم وما زالت محمّلة" },
      },
    ],
    accent: "#16374b",
  },
  {
    id: "exp-mount-sinai",
    slug: "mount-sinai-sunrise-trek",
    name: { en: "Mount Sinai Sunrise Trek", ar: "تسلق جبل موسى عند الشروق" },
    destinationSlug: "sharm-el-sheikh",
    category: "adventure",
    travelStyles: ["nature", "desert"],
    environment: "outdoor",
    groupFormat: ["shared", "private"],
    familyFriendly: false,
    durationMinutes: 780,
    priceFrom: 72,
    privateSupplement: 95,
    rating: 4.7,
    reviewCount: 359,
    maxGroupSize: 15,
    minAge: 12,
    summary: {
      en: "A night climb to 2,285 metres, sunrise at the summit and St Catherine's Monastery after.",
      ar: "صعود ليلي إلى 2,285 مترًا، وشروق الشمس من القمة، ثم زيارة دير سانت كاترين في الطريق.",
    },
    description: {
      en: "Leave Sharm around eleven at night, start walking at two, and reach the summit with an hour to spare before first light. The camel path is gradual; the last 750 steps are cut stone and steep. St Catherine's Monastery opens at nine on the way down.",
      ar: "تغادر شرم الشيخ نحو الحادية عشرة ليلًا، وتبدأ المشي في الثانية، وتبلغ القمة قبل أول الضوء بساعة كاملة. طريق الجمال تدريجي الصعود، أما الدرجات الـ750 الأخيرة فمن الحجر المنحوت وشديدة الانحدار. ويفتح دير سانت كاترين أبوابه في التاسعة، وأنت في طريق النزول.",
    },
    schedule: { en: "Set nights, 23:00 pickup", ar: "ليالٍ محددة، الاصطحاب من الفندق في 23:00" },
    meetingPoint: { en: "Hotel pickup in Sharm El Sheikh", ar: "اصطحاب من فندقك في شرم الشيخ" },
    inclusions: { en: ["Transfers and permits", "Bedouin mountain guide", "Monastery visit", "Breakfast on the descent"], ar: ["الانتقالات والتصاريح", "مرشد جبلي بدوي", "زيارة الدير", "فطور بعد النزول"] },
    exclusions: { en: ["Camel hire on the lower path", "Blanket hire at the summit", "Lunch"], ar: ["ركوب الجمل في الجزء الأول من الطريق", "إيجار بطانية عند القمة", "الغداء"] },
    whatToBring: { en: ["Head torch", "A real jacket, it is near freezing at the top", "Walking shoes with grip"], ar: ["كشاف رأس", "سترة ثقيلة، فالحرارة عند القمة تقارب الصفر", "حذاء مشي بنعل لا ينزلق"] },
    accessibility: { en: "Seven hours of walking, the final section on uneven stone steps in the dark. Good fitness required.", ar: "سبع ساعات من المشي، آخرها درجات حجرية غير منتظمة في الظلام. تحتاج إلى لياقة جيدة." },
    cancellation: { en: "Free cancellation up to 48 hours before", ar: "إلغاء مجاني حتى 48 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/mount-sinai.webp", alt: { en: "Sunrise over the Sinai mountains", ar: "شروق الشمس فوق جبال سيناء" } },
    gallery: [
      {
        src: "/images/experiences/mount-sinai-01.webp",
        alt: { en: "The Sinai ridges at first light", ar: "جبال سيناء عند أول الضوء" },
      },
      {
        src: "/images/experiences/mount-sinai-02.webp",
        alt: { en: "Saint Catherine's Monastery below the mountain", ar: "دير سانت كاترين أسفل الجبل" },
      },
    ],
    accent: "#8a3b17",
  },
  {
    id: "exp-wadi-rayan",
    slug: "wadi-el-rayan-and-whale-valley",
    name: { en: "Wadi El Rayan and Whale Valley", ar: "وادي الريان ووادي الحيتان" },
    destinationSlug: "fayoum",
    category: "nature",
    travelStyles: ["nature", "desert", "family"],
    environment: "desert",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 540,
    priceFrom: 74,
    privateSupplement: 48,
    rating: 4.8,
    reviewCount: 156,
    maxGroupSize: 10,
    minAge: null,
    summary: {
      en: "Egypt's only waterfalls in the morning, forty-million-year-old whale skeletons in the afternoon.",
      ar: "شلالات مصر الوحيدة صباحًا، وهياكل حيتان عمرها أربعون مليون سنة بعد الظهر.",
    },
    description: {
      en: "The two lakes at Wadi El Rayan are joined by a low run of falls, the only ones in the country, with dunes coming down to the water opposite. After lunch a four-wheel drive carries on to Wadi Al-Hitan, where a marked trail through open desert passes the skeletons of whales that still had hind legs. The site is UNESCO listed and the fossils are left exactly where they were found.",
      ar: "تصل بين بحيرتي وادي الريان سلسلة منخفضة من الشلالات، الوحيدة في مصر، والكثبان تنحدر حتى الماء على الضفة المقابلة. بعد الغداء تواصل سيارة الدفع الرباعي إلى وادي الحيتان، حيث يمر مسار محدد العلامات في صحراء مفتوحة بهياكل حيتان كانت لها أرجل خلفية. الموقع مسجل في قائمة اليونسكو للتراث العالمي، والأحافير باقية في مكانها كما اكتُشفت.",
    },
    schedule: { en: "Daily, 08:00 pickup", ar: "يوميًا، الاصطحاب من الفندق في 08:00" },
    meetingPoint: { en: "Hotel pickup in Fayoum, Giza or Cairo", ar: "اصطحاب من فندقك في الفيوم أو الجيزة أو القاهرة" },
    inclusions: {
      en: ["Four-wheel drive and driver", "Protected area permits", "Guide", "Lunch by the lake"],
      ar: ["سيارة دفع رباعي وسائق", "تصاريح المحمية", "مرشد", "غداء على البحيرة"],
    },
    exclusions: { en: ["Sandboard hire", "Gratuities"], ar: ["إيجار لوح التزلج على الرمال", "الإكراميات"] },
    whatToBring: {
      en: ["Closed shoes for the fossil trail", "Sun protection and water", "Swimwear in the warmer months"],
      ar: ["حذاء مغلق لمسار الأحافير", "واقٍ من الشمس وماء", "ملابس سباحة في الأشهر الدافئة"],
    },
    accessibility: {
      en: "The falls are reached on a short paved path. The Wadi Al-Hitan trail is two kilometres of loose sand and is not wheelchair accessible.",
      ar: "ممر مرصوف قصير يوصل إلى الشلالات. أما مسار وادي الحيتان فكيلومتران من الرمل الناعم، ولا يناسب الكراسي المتحركة.",
    },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: {
      src: "/images/experiences/wadi-rayan.webp",
      alt: { en: "The waterfalls at Wadi El Rayan", ar: "شلالات وادي الريان" },
    },
    gallery: [
      {
        src: "/images/experiences/wadi-rayan-01.webp",
        alt: { en: "The falls between the two lakes", ar: "الشلالات بين البحيرتين" },
      },
      {
        src: "/images/experiences/wadi-rayan-02.webp",
        alt: { en: "A whale skeleton where the sea used to be", ar: "هيكل حوت حيث كان البحر" },
      },
    ],
    accent: "#2c6e67",
  },
  {
    id: "exp-tunis-village",
    slug: "tunis-village-pottery-workshop",
    name: { en: "Tunis Village Pottery Workshop", ar: "ورشة فخار في قرية تونس" },
    destinationSlug: "fayoum",
    category: "culture",
    travelStyles: ["family", "nature"],
    environment: "indoor",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 180,
    priceFrom: 38,
    privateSupplement: 25,
    rating: 4.9,
    reviewCount: 74,
    maxGroupSize: 8,
    minAge: 6,
    summary: {
      en: "Throw a pot on the wheel in the village that turned Fayoum clay into an industry.",
      ar: "اصنع قطعة فخار على الدولاب في القرية التي حوّلت طين الفيوم إلى صناعة.",
    },
    description: {
      en: "A Swiss ceramicist opened a pottery school here in the 1980s and the village followed her into the trade. You spend an afternoon in a working studio above Lake Qarun: the clay, the wheel, the glaze, and the kiln that fires everything sold on the hill. Pieces are fired after you leave and can be collected or sent on.",
      ar: "افتتحت خزّافة سويسرية مدرسة لتعليم الفخار هنا في الثمانينيات، فتبعتها القرية كلها إلى الحرفة. تقضي بعد الظهر في ورشة عاملة تطل على بحيرة قارون: الطين، والدولاب، والطلاء الزجاجي، والفرن الذي يحرق كل ما يُباع على التل. تُحرق قطعتك بعد رحيلك، وتستلمها لاحقًا أو نرسلها إليك.",
    },
    schedule: { en: "Daily except Friday, 14:00", ar: "يوميًا عدا الجمعة، 14:00" },
    meetingPoint: { en: "Tunis Village square, Fayoum", ar: "ميدان قرية تونس، الفيوم" },
    inclusions: {
      en: ["Studio session with a village potter", "All clay and materials", "Firing of your piece", "Tea and dates"],
      ar: ["جلسة في الورشة مع خزّاف من القرية", "الطين وكل الخامات", "حرق قطعتك في الفرن", "شاي وتمر"],
    },
    exclusions: { en: ["Transfers", "Shipping of finished pieces"], ar: ["الانتقالات", "شحن القطع بعد حرقها"] },
    whatToBring: { en: ["Clothes you can get clay on", "Cash for the studio shop"], ar: ["ملابس لا يهمك أن يلطخها الطين", "نقود لمتجر الورشة"] },
    accessibility: { en: "The studio is at ground level with a single step at the door.", ar: "الورشة في الطابق الأرضي، وعند بابها درجة واحدة." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: {
      src: "/images/experiences/tunis-village.webp",
      alt: { en: "A potter working at the wheel", ar: "خزّاف يعمل على الدولاب" },
    },
    gallery: [
      {
        src: "/images/experiences/tunis-village-01.webp",
        alt: { en: "Hands on the wheel, the clay still wet", ar: "يدان على الدولاب والطين ما زال رطبًا" },
      },
      {
        src: "/images/experiences/tunis-village-02.webp",
        alt: { en: "A pottery workshop on the village lane", ar: "ورشة فخار في زقاق القرية" },
      },
    ],
    accent: "#a94a1b",
  },
  {
    id: "exp-lake-qarun",
    slug: "lake-qarun-sunset-and-birdlife",
    name: { en: "Lake Qarun Sunset and Birdlife", ar: "غروب بحيرة قارون وطيورها" },
    destinationSlug: "fayoum",
    category: "nature",
    travelStyles: ["nature", "romantic", "family"],
    environment: "water",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 150,
    priceFrom: 30,
    privateSupplement: 24,
    rating: 4.7,
    reviewCount: 61,
    maxGroupSize: 8,
    minAge: null,
    summary: {
      en: "Out on a fishing boat for the last hour of light, when the migratory flocks come in.",
      ar: "على قارب صيد في آخر ساعة من النهار، حين تعود أسراب الطيور المهاجرة.",
    },
    description: {
      en: "Lake Qarun is what remains of the ancient Lake Moeris, and the families working it have done so for a very long time. A local boat takes you along the reed edge at dusk, past egrets, flamingos in winter and whatever the nets are bringing up. Bring binoculars between November and February and the count runs into the dozens of species.",
      ar: "بحيرة قارون هي ما بقي من بحيرة موريس القديمة، والعائلات التي تصطاد فيها تفعل ذلك منذ أجيال. يأخذك قارب من قوارب الصيادين بمحاذاة حافة البوص عند الغسق، بين طيور البلشون، والفلامنجو في الشتاء، وما تجود به الشباك. احمل منظارًا بين نوفمبر وفبراير وستُحصي عشرات الأنواع.",
    },
    schedule: { en: "Daily, 90 minutes before sunset", ar: "يوميًا، قبل الغروب بتسعين دقيقة" },
    meetingPoint: { en: "Lake Qarun north shore landing", ar: "المرسى على الشاطئ الشمالي لبحيرة قارون" },
    inclusions: { en: ["Private or shared boat with its owner", "Tea aboard", "Binoculars on request"], ar: ["قارب خاص أو مشترك يقوده صاحبه", "شاي على القارب", "منظار عند الطلب"] },
    exclusions: { en: ["Transfers", "Dinner"], ar: ["الانتقالات", "العشاء"] },
    whatToBring: { en: ["A layer for after sunset", "Binoculars if you have them"], ar: ["سترة خفيفة لما بعد الغروب", "منظار إن كان لديك"] },
    accessibility: { en: "Boarding is a step down from a low jetty into an open boat with no rail.", ar: "الركوب بخطوة نزول من رصيف منخفض إلى قارب مفتوح بلا حاجز." },
    cancellation: { en: "Free cancellation up to 12 hours before", ar: "إلغاء مجاني حتى 12 ساعة قبل الموعد" },
    heroImage: {
      src: "/images/experiences/lake-qarun.webp",
      alt: { en: "A fishing boat and birds on Lake Qarun", ar: "قارب صيد وطيور في بحيرة قارون" },
    },
    gallery: [
      {
        src: "/images/experiences/lake-qarun-01.webp",
        alt: { en: "Fishermen working the lake, egrets waiting", ar: "صيادون في البحيرة وطيور البلشون تنتظر" },
      },
      {
        src: "/images/experiences/lake-qarun-02.webp",
        alt: { en: "A rowing boat out on the flat water", ar: "قارب تجديف على الماء الساكن" },
      },
    ],
    accent: "#2a719a",
  },
];

export const experienceBySlug = new Map(experiences.map((e) => [e.slug, e]));

/**
 * The six the homepage leads with, matching the categories the brief names:
 * a balloon ride, a Nile cruise, a pyramid tour, desert camping, diving and a
 * Nubian village visit.
 */
export const homepageExperienceSlugs = [
  "luxor-hot-air-balloon",
  "nile-cruise-aswan-to-luxor",
  "giza-pyramids-at-sunrise",
  "white-desert-overnight-camp",
  "ras-mohammed-diving-day",
  "nubian-village-lunch",
] as const;

export const homepageExperiences = homepageExperienceSlugs.map((slug) => {
  const experience = experiences.find((e) => e.slug === slug);
  if (!experience) throw new Error(`Unknown homepage experience: ${slug}`);
  return experience;
});

export const experiencesByDestination = experiences.reduce<Record<string, Experience[]>>(
  (acc, exp) => {
    (acc[exp.destinationSlug] ??= []).push(exp);
    return acc;
  },
  {},
);
