import type { Experience } from "./types";

/**
 * Twenty-four bookable experiences across all eight destinations, covering
 * every category the marketplace filters on: culture, history, adventure,
 * food, nature, wellness, nightlife and water.
 */
export const experiences: Experience[] = [
  {
    id: "exp-giza-sunrise",
    slug: "giza-pyramids-at-sunrise",
    name: { en: "Giza Pyramids at Sunrise", ar: "أهرامات الجيزة عند الشروق" },
    destinationSlug: "cairo",
    category: "history",
    travelStyles: ["history", "family", "romantic"],
    environment: "outdoor",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 240,
    priceFrom: 78,
    privateSupplement: 45,
    rating: 4.9,
    reviewCount: 412,
    maxGroupSize: 12,
    minAge: null,
    summary: {
      en: "Enter the plateau as the gates open, with an Egyptologist and two hours before the coaches.",
      ar: "ادخل الهضبة مع فتح البوابات، بصحبة عالم مصريات وقبل وصول الحافلات بساعتين.",
    },
    description: {
      en: "The plateau opens at eight and empties of atmosphere by ten, so this tour starts at seven. You walk the Great Pyramid's north face while the light is still low, take the panorama point before it fills, and finish at the Sphinx from the valley temple causeway. An Egyptologist stays with the group throughout and answers the questions guidebooks skip.",
      ar: "تفتح الهضبة عند الثامنة وتفقد سحرها بحلول العاشرة، ولذلك تبدأ هذه الجولة عند السابعة. تسير على الواجهة الشمالية للهرم الأكبر والضوء ما زال منخفضًا، وتصل إلى نقطة البانوراما قبل امتلائها، وتختم عند أبي الهول من طريق معبد الوادي. ويرافق المجموعة عالم مصريات طوال الوقت ويجيب عن الأسئلة التي تتخطاها الأدلة السياحية.",
    },
    schedule: { en: "Daily, 07:00 pickup", ar: "يوميًا، الانطلاق 07:00" },
    meetingPoint: { en: "Hotel pickup within Cairo or Giza", ar: "الانطلاق من فندقك داخل القاهرة أو الجيزة" },
    inclusions: {
      en: ["Licensed Egyptologist guide", "Hotel transfers in an air-conditioned vehicle", "Plateau entry ticket", "Bottled water"],
      ar: ["مرشد مصريات مرخص", "انتقالات من الفندق بسيارة مكيفة", "تذكرة دخول الهضبة", "مياه معبأة"],
    },
    exclusions: {
      en: ["Entry inside the Great Pyramid", "Camel or horse rides", "Gratuities"],
      ar: ["الدخول إلى داخل الهرم الأكبر", "ركوب الجمال أو الخيل", "الإكراميات"],
    },
    whatToBring: {
      en: ["Closed shoes for sand and rubble", "Hat and sunscreen", "Small notes for the photography fee"],
      ar: ["حذاء مغلق للرمل والحصى", "قبعة وواقٍ من الشمس", "فئات نقدية صغيرة لرسوم التصوير"],
    },
    accessibility: {
      en: "The plateau road is paved and drivable, so wheelchair users can reach every viewpoint. Entering the pyramid interior is not step-free.",
      ar: "طريق الهضبة معبد وصالح للسيارات، ويمكن لمستخدمي الكراسي المتحركة الوصول إلى كل نقاط المشاهدة. أما الدخول إلى داخل الهرم فغير خالٍ من الدرج.",
    },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/giza-sunrise.webp", alt: { en: "Riders below the pyramid of Khafre", ar: "فرسان أسفل هرم خفرع" } },
    gallery: [],
    accent: "#c85f26",
  },
  {
    id: "exp-gem-tour",
    slug: "grand-egyptian-museum-guided",
    name: { en: "Grand Egyptian Museum, Guided", ar: "المتحف المصري الكبير بصحبة مرشد" },
    destinationSlug: "cairo",
    category: "culture",
    travelStyles: ["history", "family", "luxury"],
    environment: "indoor",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 270,
    priceFrom: 64,
    privateSupplement: 40,
    rating: 4.8,
    reviewCount: 356,
    maxGroupSize: 14,
    minAge: null,
    summary: {
      en: "Half a day in the world's largest archaeological museum, with a route that skips the queue-shaped mistakes.",
      ar: "نصف يوم في أكبر متحف أثري في العالم، بمسار يتجنب أخطاء الازدحام المعتادة.",
    },
    description: {
      en: "Fifty thousand objects will exhaust anyone without a plan. Your guide takes the grand staircase chronologically, spends the middle of the visit in the two Tutankhamun galleries, and leaves the solar boat for the end. Expect roughly four hours inside with a coffee break at the atrium.",
      ar: "خمسون ألف قطعة كفيلة بإنهاك أي زائر بلا خطة. يأخذك المرشد عبر الدرج العظيم ترتيبًا زمنيًا، ويقضي منتصف الزيارة في قاعتي توت عنخ آمون، ويترك مركب الشمس للنهاية. توقع نحو أربع ساعات في الداخل مع استراحة قهوة في البهو.",
    },
    schedule: { en: "Daily except Tuesday, 09:30 and 13:30", ar: "يوميًا عدا الثلاثاء، 09:30 و13:30" },
    meetingPoint: { en: "Museum main entrance, Giza", ar: "المدخل الرئيسي للمتحف، الجيزة" },
    inclusions: {
      en: ["Egyptologist guide", "Museum entry ticket", "Audio headsets for larger groups"],
      ar: ["مرشد مصريات", "تذكرة دخول المتحف", "سماعات صوتية للمجموعات الكبيرة"],
    },
    exclusions: { en: ["Transfers", "Food and drink", "Tutankhamun gallery photography fee"], ar: ["الانتقالات", "الطعام والشراب", "رسوم التصوير في قاعة توت عنخ آمون"] },
    whatToBring: { en: ["Comfortable shoes", "A light layer for the air conditioning"], ar: ["حذاء مريح", "طبقة خفيفة لتكييف الهواء"] },
    accessibility: { en: "Step-free throughout, with lifts to every level and wheelchairs available at the entrance.", ar: "خالٍ من الدرج بالكامل، وبه مصاعد إلى كل الطوابق وكراسٍ متحركة متاحة عند المدخل." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/gem-atrium.webp", alt: { en: "The museum atrium and colossal statue", ar: "بهو المتحف والتمثال الضخم" } },
    gallery: [],
    accent: "#a8853b",
  },
  {
    id: "exp-khan-food",
    slug: "khan-el-khalili-food-walk",
    name: { en: "Khan el-Khalili Food Walk", ar: "جولة طعام في خان الخليلي" },
    destinationSlug: "cairo",
    category: "food",
    travelStyles: ["family", "history"],
    environment: "urban",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 210,
    priceFrom: 52,
    privateSupplement: 30,
    rating: 4.9,
    reviewCount: 288,
    maxGroupSize: 10,
    minAge: null,
    summary: {
      en: "Seven tastings through the old market, from koshary counters to the oldest coffee house in Cairo.",
      ar: "سبع محطات تذوق في السوق القديم، من محلات الكشري إلى أقدم مقهى في القاهرة.",
    },
    description: {
      en: "A walking route through Fatimid Cairo built entirely around what people actually eat: koshary, hawawshi off the grill, fresh sugarcane juice, feteer sweet and savoury, and mint tea at El Fishawy, which has been open since 1773. Enough food to replace dinner.",
      ar: "مسار سيرًا داخل القاهرة الفاطمية مبني بالكامل على ما يأكله الناس فعلًا: كشري وحواوشي من على الفحم وعصير قصب طازج وفطير حلو ومالح وشاي بالنعناع في الفيشاوي المفتوح منذ عام 1773. طعام يكفي ليحل محل العشاء.",
    },
    schedule: { en: "Sunday to Thursday, 17:00", ar: "من الأحد إلى الخميس، 17:00" },
    meetingPoint: { en: "Al-Hussein Square, by the mosque gate", ar: "ميدان الحسين، عند باب المسجد" },
    inclusions: { en: ["All seven tastings", "Local food guide", "Tea at El Fishawy"], ar: ["محطات التذوق السبع جميعها", "مرشد طعام محلي", "شاي في الفيشاوي"] },
    exclusions: { en: ["Transfers", "Additional drinks", "Shopping"], ar: ["الانتقالات", "المشروبات الإضافية", "التسوق"] },
    whatToBring: { en: ["An empty stomach", "Cash for souvenirs"], ar: ["معدة خالية", "نقود للهدايا التذكارية"] },
    accessibility: { en: "Cobbled and busy underfoot. Tell us in advance and we will adjust the route for limited mobility.", ar: "الأرضية حصوية ومزدحمة. أخبرنا مسبقًا لنعدّل المسار لمن لديه صعوبة في الحركة." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/khan-food.webp", alt: { en: "Street food stall in the old market", ar: "عربة طعام في السوق القديم" } },
    gallery: [],
    accent: "#c85f26",
  },
  {
    id: "exp-muizz-night",
    slug: "islamic-cairo-night-walk",
    name: { en: "Islamic Cairo After Dark", ar: "القاهرة الإسلامية بعد الغروب" },
    destinationSlug: "cairo",
    category: "culture",
    travelStyles: ["history", "romantic"],
    environment: "urban",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 180,
    priceFrom: 44,
    privateSupplement: 28,
    rating: 4.8,
    reviewCount: 197,
    maxGroupSize: 12,
    minAge: null,
    summary: {
      en: "Al-Muizz Street lit and closed to cars, from Bab al-Futuh to the Ghuri complex.",
      ar: "شارع المعز مضاءً ومغلقًا أمام السيارات، من باب الفتوح إلى مجمع الغوري.",
    },
    description: {
      en: "One kilometre of continuous medieval architecture, walked in the two hours when it looks its best. Minarets are floodlit, the street is pedestrianised, and a rooftop stop above the Qalawun complex gives you the skyline that put the phrase 'city of a thousand minarets' into circulation.",
      ar: "كيلومتر متصل من العمارة الوسيطة، يُقطع سيرًا في الساعتين اللتين يبدو فيهما في أبهى حال. المآذن مضاءة والشارع للمشاة، ووقفة على سطح فوق مجمع قلاوون تمنحك الأفق الذي أطلق عبارة «مدينة الألف مئذنة».",
    },
    schedule: { en: "Daily, 18:30", ar: "يوميًا، 18:30" },
    meetingPoint: { en: "Bab al-Futuh gate", ar: "بوابة باب الفتوح" },
    inclusions: { en: ["Guide", "Mosque entries where ticketed", "Rooftop tea"], ar: ["مرشد", "دخول المساجد حيث تُطلب تذاكر", "شاي على السطح"] },
    exclusions: { en: ["Transfers", "Dinner"], ar: ["الانتقالات", "العشاء"] },
    whatToBring: { en: ["Shoulders and knees covered", "A scarf for mosque visits"], ar: ["لباس يغطي الكتفين والركبتين", "وشاح لزيارة المساجد"] },
    accessibility: { en: "Mostly flat and paved. Two mosque courtyards have a single step.", ar: "المسار مستوٍ ومرصوف في معظمه. وفي فناءي مسجدين درجة واحدة." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/muizz-night.webp", alt: { en: "Lit minarets along Al-Muizz Street", ar: "مآذن مضاءة في شارع المعز" } },
    gallery: [],
    accent: "#a8853b",
  },
  {
    id: "exp-nile-dinner",
    slug: "nile-dinner-cruise-cairo",
    name: { en: "Nile Dinner Cruise", ar: "عشاء في رحلة نيلية" },
    destinationSlug: "cairo",
    category: "nightlife",
    travelStyles: ["romantic", "family", "luxury"],
    environment: "water",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 150,
    priceFrom: 58,
    privateSupplement: 120,
    rating: 4.6,
    reviewCount: 524,
    maxGroupSize: 60,
    minAge: null,
    summary: {
      en: "Two hours on the water with an open buffet, live oud and the city lit on both banks.",
      ar: "ساعتان على الماء مع بوفيه مفتوح وعزف عود حي والمدينة مضاءة على الضفتين.",
    },
    description: {
      en: "A calm, unhurried loop between Zamalek and Garden City while dinner is served. The set includes a live oud player and a tanoura dancer, and the upper deck stays open all evening for anyone who would rather watch the bridges than the show.",
      ar: "دورة هادئة غير عجولة بين الزمالك وجاردن سيتي أثناء تقديم العشاء. تتضمن الفقرة عازف عود حيًا وراقص تنورة، ويبقى السطح العلوي مفتوحًا طوال السهرة لمن يفضل مشاهدة الكباري على العرض.",
    },
    schedule: { en: "Daily, 19:30 and 21:45", ar: "يوميًا، 19:30 و21:45" },
    meetingPoint: { en: "Boat mooring, Corniche El Nil, Giza", ar: "مرسى المركب، كورنيش النيل، الجيزة" },
    inclusions: { en: ["Open buffet dinner", "Live music and tanoura show", "Soft drinks"], ar: ["عشاء بوفيه مفتوح", "موسيقى حية وعرض تنورة", "مشروبات غازية"] },
    exclusions: { en: ["Hotel transfers", "Alcoholic drinks"], ar: ["الانتقالات من الفندق", "المشروبات الكحولية"] },
    whatToBring: { en: ["Smart casual dress", "A light jacket in winter"], ar: ["ملابس شبه رسمية", "سترة خفيفة في الشتاء"] },
    accessibility: { en: "A short gangway with a handrail. Step-free once aboard the main deck.", ar: "ممر قصير بمسند يد. وخالٍ من الدرج بعد الصعود إلى السطح الرئيسي." },
    cancellation: { en: "Free cancellation up to 48 hours before", ar: "إلغاء مجاني حتى 48 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/nile-dinner.webp", alt: { en: "The Nile at dusk in Cairo", ar: "النيل عند الغسق في القاهرة" } },
    gallery: [],
    accent: "#2a719a",
  },
  {
    id: "exp-saqqara",
    slug: "saqqara-and-dahshur-day",
    name: { en: "Saqqara and Dahshur Day", ar: "يوم في سقارة ودهشور" },
    destinationSlug: "cairo",
    category: "history",
    travelStyles: ["history"],
    environment: "outdoor",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 420,
    priceFrom: 88,
    privateSupplement: 55,
    rating: 4.9,
    reviewCount: 214,
    maxGroupSize: 12,
    minAge: null,
    summary: {
      en: "The Step Pyramid, the Bent Pyramid and the Red Pyramid, all without the Giza crowds.",
      ar: "الهرم المدرج والهرم المائل والهرم الأحمر، جميعها بلا زحام الجيزة.",
    },
    description: {
      en: "Djoser's Step Pyramid is the oldest stone building on earth and the necropolis around it holds mastabas with carving far finer than anything at Giza. Dahshur adds the two pyramids where the geometry was worked out, and you can walk down into the Red Pyramid with no queue at all.",
      ar: "هرم زوسر المدرج أقدم بناء حجري على وجه الأرض، وتضم الجبانة حوله مصاطب بنقوش أدق بكثير من أي شيء في الجيزة. وتضيف دهشور الهرمين اللذين ضُبطت فيهما الهندسة، ويمكنك النزول إلى داخل الهرم الأحمر بلا طابور إطلاقًا.",
    },
    schedule: { en: "Daily, 08:00 pickup", ar: "يوميًا، الانطلاق 08:00" },
    meetingPoint: { en: "Hotel pickup within Cairo or Giza", ar: "الانطلاق من فندقك داخل القاهرة أو الجيزة" },
    inclusions: { en: ["Egyptologist guide", "All site entry tickets", "Air-conditioned transfers", "Lunch"], ar: ["مرشد مصريات", "تذاكر دخول جميع المواقع", "انتقالات مكيفة", "غداء"] },
    exclusions: { en: ["Gratuities", "Photography fees inside tombs"], ar: ["الإكراميات", "رسوم التصوير داخل المقابر"] },
    whatToBring: { en: ["Sun protection", "Water", "Shoes you can climb a shaft in"], ar: ["واقٍ من الشمس", "ماء", "حذاء يصلح للنزول في ممر ضيق"] },
    accessibility: { en: "Site paths are sandy and uneven. Pyramid interiors involve a steep, low, ducked descent.", ar: "مسارات المواقع رملية وغير مستوية. والنزول داخل الأهرامات يتطلب انحناءً في ممر منحدر منخفض." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/saqqara.webp", alt: { en: "The Step Pyramid of Djoser", ar: "هرم زوسر المدرج" } },
    gallery: [],
    accent: "#9a7a54",
  },
  {
    id: "exp-alex-greco",
    slug: "alexandria-greco-roman-day",
    name: { en: "Greco-Roman Alexandria", ar: "الإسكندرية اليونانية الرومانية" },
    destinationSlug: "alexandria",
    category: "history",
    travelStyles: ["history", "family"],
    environment: "urban",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 360,
    priceFrom: 62,
    privateSupplement: 40,
    rating: 4.7,
    reviewCount: 168,
    maxGroupSize: 12,
    minAge: null,
    summary: {
      en: "Catacombs, Pompey's Pillar, the Roman theatre and Qaitbay Citadel in one well-ordered day.",
      ar: "السراديب وعمود السواري والمسرح الروماني وقلعة قايتباي في يوم واحد محكم الترتيب.",
    },
    description: {
      en: "Alexandria's ancient layer is scattered across the modern city, which is why doing it with a driver and a route makes the difference. The day ends at Qaitbay on the harbour wall, standing on the foundations of the lighthouse.",
      ar: "طبقة الإسكندرية القديمة مبعثرة في المدينة الحديثة، ولهذا يصنع وجود سائق ومسار مرتب فارقًا حقيقيًا. وينتهي اليوم عند قايتباي على سور الميناء، فوق أساسات الفنار.",
    },
    schedule: { en: "Daily except Monday, 09:00", ar: "يوميًا عدا الاثنين، 09:00" },
    meetingPoint: { en: "Hotel pickup in Alexandria", ar: "الانطلاق من فندقك في الإسكندرية" },
    inclusions: { en: ["Guide", "All entry tickets", "Air-conditioned vehicle"], ar: ["مرشد", "جميع تذاكر الدخول", "سيارة مكيفة"] },
    exclusions: { en: ["Lunch", "Gratuities"], ar: ["الغداء", "الإكراميات"] },
    whatToBring: { en: ["Walking shoes", "A windproof layer in winter"], ar: ["حذاء للمشي", "طبقة تقي الرياح في الشتاء"] },
    accessibility: { en: "The catacombs descend a spiral staircase with no lift. Everything else is largely step-free.", ar: "يُنزل إلى السراديب عبر سلم حلزوني بلا مصعد. أما بقية المواقع فخالية من الدرج إلى حد كبير." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/alex-catacombs.webp", alt: { en: "Carved chamber in the catacombs", ar: "حجرة منحوتة في السراديب" } },
    gallery: [],
    accent: "#2a719a",
  },
  {
    id: "exp-alex-seafood",
    slug: "alexandria-seafood-cooking-class",
    name: { en: "Mediterranean Seafood Class", ar: "درس طهي المأكولات البحرية المتوسطية" },
    destinationSlug: "alexandria",
    category: "food",
    travelStyles: ["family", "romantic"],
    environment: "indoor",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 240,
    priceFrom: 70,
    privateSupplement: 45,
    rating: 4.9,
    reviewCount: 96,
    maxGroupSize: 8,
    minAge: 10,
    summary: {
      en: "Buy the catch at the fish market, then cook it four ways in a family kitchen above the harbour.",
      ar: "اشترِ الصيد من سوق السمك، ثم اطبخه بأربع طرق في مطبخ عائلي يطل على الميناء.",
    },
    description: {
      en: "Start at the Anfoushi fish market choosing sea bass, calamari and shrimp with your host, who will explain how Alexandrians judge freshness. Cook singari-style baked fish, garlic shrimp, a tahini salad and rice with a sea-facing balcony, then eat what you made.",
      ar: "ابدأ في سوق سمك الأنفوشي باختيار القاروص والكاليماري والجمبري مع مضيفك الذي يشرح كيف يميّز أهل الإسكندرية الطازج. اطبخ سمكًا صنجاريًا في الفرن وجمبريًا بالثوم وسلطة طحينة وأرزًا في شرفة تطل على البحر، ثم تناول ما صنعت.",
    },
    schedule: { en: "Tuesday, Thursday and Saturday, 11:00", ar: "الثلاثاء والخميس والسبت، 11:00" },
    meetingPoint: { en: "Anfoushi fish market entrance", ar: "مدخل سوق سمك الأنفوشي" },
    inclusions: { en: ["Market tour and all ingredients", "Cooking class with a local host", "The full meal you cook", "Recipe cards in English and Arabic"], ar: ["جولة في السوق وجميع المكونات", "درس طهي مع مضيف محلي", "الوجبة الكاملة التي تطبخها", "بطاقات وصفات بالعربية والإنجليزية"] },
    exclusions: { en: ["Transfers", "Alcoholic drinks"], ar: ["الانتقالات", "المشروبات الكحولية"] },
    whatToBring: { en: ["An appetite", "Shellfish allergies declared at booking"], ar: ["شهية مفتوحة", "الإفصاح عن حساسية القشريات عند الحجز"] },
    accessibility: { en: "The kitchen is on the first floor and reached by stairs only.", ar: "المطبخ في الطابق الأول ولا يُوصل إليه إلا بالسلم." },
    cancellation: { en: "Free cancellation up to 48 hours before", ar: "إلغاء مجاني حتى 48 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/alex-seafood.webp", alt: { en: "Choosing the catch at the fish market", ar: "اختيار الصيد في سوق السمك" } },
    gallery: [],
    accent: "#2c6e67",
  },
  {
    id: "exp-luxor-balloon",
    slug: "luxor-hot-air-balloon",
    name: { en: "Hot Air Balloon over the Valley", ar: "منطاد فوق وادي الملوك" },
    destinationSlug: "luxor",
    category: "adventure",
    travelStyles: ["romantic", "luxury", "history"],
    environment: "outdoor",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 180,
    priceFrom: 125,
    privateSupplement: 480,
    rating: 4.9,
    reviewCount: 731,
    maxGroupSize: 20,
    minAge: 6,
    summary: {
      en: "Forty-five minutes over the Theban necropolis as the sun comes up behind Karnak.",
      ar: "خمس وأربعون دقيقة فوق جبانة طيبة والشمس تشرق خلف الكرنك.",
    },
    description: {
      en: "Cross the river in the dark, watch the envelopes inflate on the launch field, and lift off in time to see first light hit Hatshepsut's terraces. The flight drifts over the Valley of the Kings, the Colossi of Memnon and the green strip of farmland before setting down in a field.",
      ar: "اعبر النهر في العتمة، وشاهد أغلفة المناطيد تنتفخ في ساحة الإقلاع، وارتفع في وقت يتيح لك رؤية أول الضوء يلامس مدرجات حتشبسوت. تنساب الرحلة فوق وادي الملوك وتمثالي ممنون وشريط الزراعة الأخضر قبل الهبوط في حقل.",
    },
    schedule: { en: "Daily at dawn, subject to wind", ar: "يوميًا عند الفجر، رهنًا بحالة الرياح" },
    meetingPoint: { en: "Hotel pickup, roughly 04:30 in winter", ar: "الانطلاق من الفندق، نحو 04:30 شتاءً" },
    inclusions: { en: ["Transfers and river crossing", "45-minute flight", "Flight certificate", "Light breakfast"], ar: ["الانتقالات وعبور النهر", "رحلة طيران 45 دقيقة", "شهادة طيران", "فطور خفيف"] },
    exclusions: { en: ["Gratuity for the ground crew", "Hotel breakfast you will miss"], ar: ["إكرامية طاقم الأرض", "فطور الفندق الذي ستفوّته"] },
    whatToBring: { en: ["A warm layer for dawn", "Camera strap, not a loose phone"], ar: ["طبقة دافئة للفجر", "حزام كاميرا، لا هاتف غير مثبت"] },
    accessibility: { en: "Boarding means climbing over the basket wall, roughly one metre high, unaided.", ar: "يتطلب الصعود تسلق جدار السلة بارتفاع متر تقريبًا دون مساعدة." },
    cancellation: { en: "Full refund if cancelled for weather, which happens often and without warning", ar: "استرداد كامل عند الإلغاء بسبب الطقس، وهو أمر متكرر ويحدث دون إنذار" },
    heroImage: { src: "/images/experiences/luxor-balloon.webp", alt: { en: "Balloons over the west bank at dawn", ar: "مناطيد فوق الضفة الغربية عند الفجر" } },
    gallery: [],
    accent: "#c85f26",
  },
  {
    id: "exp-valley-kings",
    slug: "valley-of-the-kings-private",
    name: { en: "Valley of the Kings, Privately", ar: "وادي الملوك بصحبة خاصة" },
    destinationSlug: "luxor",
    category: "history",
    travelStyles: ["history", "luxury"],
    environment: "outdoor",
    groupFormat: ["private"],
    familyFriendly: true,
    durationMinutes: 300,
    priceFrom: 110,
    privateSupplement: 0,
    rating: 4.9,
    reviewCount: 289,
    maxGroupSize: 6,
    minAge: null,
    summary: {
      en: "Five tombs including Seti I, chosen for painting quality rather than fame, with an Egyptologist.",
      ar: "خمس مقابر منها مقبرة سيتي الأول، مختارة بحسب جودة النقوش لا الشهرة، بصحبة عالم مصريات.",
    },
    description: {
      en: "Your guide picks the day's tombs based on which are open and least busy, then adds Seti I, the longest and most completely painted tomb in the valley. The morning finishes at Hatshepsut's terraces and Medinet Habu, where the original colour survives on the ceilings.",
      ar: "يختار مرشدك مقابر اليوم بحسب المفتوح منها والأقل ازدحامًا، ثم يضيف مقبرة سيتي الأول، أطول مقابر الوادي وأكملها زخرفة. وينتهي الصباح عند مدرجات حتشبسوت ومدينة هابو حيث تبقى الألوان الأصلية على الأسقف.",
    },
    schedule: { en: "Daily, 06:30 pickup", ar: "يوميًا، الانطلاق 06:30" },
    meetingPoint: { en: "Hotel pickup, either bank", ar: "الانطلاق من الفندق على أي من الضفتين" },
    inclusions: { en: ["Private Egyptologist", "Valley entry with three tombs", "Seti I supplementary ticket", "Private vehicle and water"], ar: ["عالم مصريات خاص", "دخول الوادي مع ثلاث مقابر", "تذكرة سيتي الأول الإضافية", "سيارة خاصة ومياه"] },
    exclusions: { en: ["Tutankhamun's tomb ticket", "Photography permit", "Lunch"], ar: ["تذكرة مقبرة توت عنخ آمون", "تصريح التصوير", "الغداء"] },
    whatToBring: { en: ["Hat, water, sunscreen", "Cash for the photo permit"], ar: ["قبعة وماء وواقٍ من الشمس", "نقود لتصريح التصوير"] },
    accessibility: { en: "A shuttle runs to the tomb entrances, but the tombs themselves are ramped or stepped descents with no handrails.", ar: "توجد عربة نقل إلى مداخل المقابر، لكن المقابر نفسها منحدرات أو درجات نازلة بلا مساند." },
    cancellation: { en: "Free cancellation up to 48 hours before", ar: "إلغاء مجاني حتى 48 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/valley-kings.webp", alt: { en: "Painted tomb wall in the Valley of the Kings", ar: "جدار مقبرة مزخرف في وادي الملوك" } },
    gallery: [],
    accent: "#a8853b",
  },
  {
    id: "exp-karnak-sound",
    slug: "karnak-sound-and-light",
    name: { en: "Karnak Sound and Light", ar: "الصوت والضوء في الكرنك" },
    destinationSlug: "luxor",
    category: "culture",
    travelStyles: ["history", "family", "romantic"],
    environment: "outdoor",
    groupFormat: ["shared"],
    familyFriendly: true,
    durationMinutes: 90,
    priceFrom: 32,
    privateSupplement: 0,
    rating: 4.4,
    reviewCount: 143,
    maxGroupSize: 40,
    minAge: null,
    summary: {
      en: "The temple after closing, walked in the dark while it is lit hall by hall.",
      ar: "المعبد بعد إغلاقه، يُقطع سيرًا في الظلام بينما يُضاء بهوًا بعد بهو.",
    },
    description: {
      en: "The audience moves through Karnak rather than sitting in front of it. The narration is theatrical and the history is broad-brush, but standing among 134 lit columns with the site otherwise empty is worth the ticket on its own.",
      ar: "يتحرك الجمهور داخل الكرنك بدلًا من الجلوس أمامه. السرد مسرحي والتاريخ عام في تفاصيله، لكن الوقوف بين مئة وأربعة وثلاثين عمودًا مضاءً والموقع خالٍ يستحق التذكرة وحده.",
    },
    schedule: { en: "Nightly, in English or Arabic depending on the session", ar: "كل ليلة، بالإنجليزية أو العربية بحسب العرض" },
    meetingPoint: { en: "Karnak Temple main gate", ar: "البوابة الرئيسية لمعبد الكرنك" },
    inclusions: { en: ["Show ticket", "Multilingual headset"], ar: ["تذكرة العرض", "سماعة متعددة اللغات"] },
    exclusions: { en: ["Transfers", "Guide"], ar: ["الانتقالات", "المرشد"] },
    whatToBring: { en: ["Flat shoes for uneven stone", "A light jacket"], ar: ["حذاء مسطح للحجر غير المستوي", "سترة خفيفة"] },
    accessibility: { en: "The route crosses uneven ancient paving in low light and is not suitable for wheelchairs.", ar: "يمر المسار على بلاط قديم غير مستوٍ في إضاءة خافتة، وهو غير مناسب للكراسي المتحركة." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/karnak-night.webp", alt: { en: "The obelisk at Karnak in late light", ar: "مسلة الكرنك في ضوء آخر النهار" } },
    gallery: [],
    accent: "#8a3b17",
  },
  {
    id: "exp-abu-simbel",
    slug: "abu-simbel-sunrise",
    name: { en: "Abu Simbel at Sunrise", ar: "أبو سمبل عند الشروق" },
    destinationSlug: "aswan",
    category: "history",
    travelStyles: ["history", "luxury"],
    environment: "outdoor",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 600,
    priceFrom: 105,
    privateSupplement: 90,
    rating: 4.9,
    reviewCount: 466,
    maxGroupSize: 14,
    minAge: null,
    summary: {
      en: "Three hours south before dawn to reach the colossi in the first light, then back by afternoon.",
      ar: "ثلاث ساعات جنوبًا قبل الفجر للوصول إلى التماثيل في أول الضوء، ثم العودة بعد الظهر.",
    },
    description: {
      en: "Ramesses II cut four twenty-metre figures into a cliff, and in the 1960s the whole temple was sawn into blocks and lifted sixty metres to escape Lake Nasser. Arriving at opening means seeing the facade lit orange with almost nobody in the frame.",
      ar: "نحت رمسيس الثاني أربعة تماثيل بارتفاع عشرين مترًا في جرف، وفي الستينيات قُطع المعبد كله إلى كتل ورُفع ستين مترًا هربًا من بحيرة ناصر. والوصول عند الفتح يعني رؤية الواجهة متوهجة بالبرتقالي وبلا أحد تقريبًا في الصورة.",
    },
    schedule: { en: "Daily, 04:00 departure by road", ar: "يوميًا، المغادرة 04:00 برًا" },
    meetingPoint: { en: "Hotel pickup in Aswan", ar: "الانطلاق من فندقك في أسوان" },
    inclusions: { en: ["Air-conditioned road transfer", "Egyptologist guide", "Temple entry tickets", "Breakfast box"], ar: ["انتقال بري مكيف", "مرشد مصريات", "تذاكر دخول المعبدين", "علبة فطور"] },
    exclusions: { en: ["Flight upgrade", "Lunch", "Gratuities"], ar: ["الترقية إلى الطيران", "الغداء", "الإكراميات"] },
    whatToBring: { en: ["Passport for the checkpoint", "Sun protection", "Something to sleep on in the van"], ar: ["جواز السفر لنقطة التفتيش", "واقٍ من الشمس", "ما تنام عليه في السيارة"] },
    accessibility: { en: "Step-free from the car park to the temple terrace along a paved path.", ar: "خالٍ من الدرج من الموقف إلى شرفة المعبد عبر ممر مرصوف." },
    cancellation: { en: "Free cancellation up to 48 hours before", ar: "إلغاء مجاني حتى 48 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/abu-simbel.webp", alt: { en: "The pillared hall inside Abu Simbel", ar: "بهو الأعمدة داخل أبو سمبل" } },
    gallery: [],
    accent: "#c85f26",
  },
  {
    id: "exp-nubian-village",
    slug: "nubian-village-lunch",
    name: { en: "Nubian Village Lunch", ar: "غداء في قرية نوبية" },
    destinationSlug: "aswan",
    category: "culture",
    travelStyles: ["family", "romantic", "nature"],
    environment: "outdoor",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 240,
    priceFrom: 48,
    privateSupplement: 30,
    rating: 4.8,
    reviewCount: 205,
    maxGroupSize: 10,
    minAge: null,
    summary: {
      en: "A motorboat across to Gharb Soheil for a home-cooked meal in an indigo courtyard.",
      ar: "عبور بقارب إلى غرب سهيل لوجبة منزلية في فناء أزرق نيلي.",
    },
    description: {
      en: "The Nubian villages upstream of Aswan paint their houses in flat blocks of indigo, ochre and rose. Lunch is served in a family courtyard: slow-cooked tagine, fresh bread, hibiscus, and an hour of conversation about a culture displaced twice by dams.",
      ar: "تصبغ القرى النوبية جنوب أسوان بيوتها بكتل مسطحة من النيلي والمغرة والوردي. ويُقدَّم الغداء في فناء عائلي: طاجن بطيء الطهي وخبز طازج وكركديه وساعة من الحديث عن ثقافة هُجِّرت مرتين بسبب السدود.",
    },
    schedule: { en: "Daily, 11:00", ar: "يوميًا، 11:00" },
    meetingPoint: { en: "Aswan public boat landing", ar: "مرسى القوارب العام في أسوان" },
    inclusions: { en: ["Return motorboat", "Home-cooked lunch", "Village host and guide", "Hibiscus and tea"], ar: ["قارب ذهابًا وإيابًا", "غداء منزلي", "مضيف ومرشد من القرية", "كركديه وشاي"] },
    exclusions: { en: ["Camel ride option", "Souvenirs"], ar: ["خيار ركوب الجمل", "الهدايا التذكارية"] },
    whatToBring: { en: ["Modest clothing", "Cash for handicrafts"], ar: ["ملابس محتشمة", "نقود للحرف اليدوية"] },
    accessibility: { en: "Boarding is from a low jetty and the village lanes are sand. Assistance can be arranged on request.", ar: "الصعود من رصيف منخفض، وأزقة القرية رملية. ويمكن ترتيب المساعدة عند الطلب." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/nubian-village.webp", alt: { en: "Painted Nubian houses above the Nile", ar: "بيوت نوبية ملونة فوق النيل" } },
    gallery: [],
    accent: "#2a719a",
  },
  {
    id: "exp-felucca-sunset",
    slug: "felucca-sunset-sail",
    name: { en: "Felucca Sunset Sail", ar: "إبحار في فلوكة عند الغروب" },
    destinationSlug: "aswan",
    category: "nature",
    travelStyles: ["romantic", "family", "nature"],
    environment: "water",
    groupFormat: ["private", "shared"],
    familyFriendly: true,
    durationMinutes: 120,
    priceFrom: 26,
    privateSupplement: 35,
    rating: 4.9,
    reviewCount: 612,
    maxGroupSize: 8,
    minAge: null,
    summary: {
      en: "Two hours under sail around Elephantine and Kitchener's Island, engine off the whole way.",
      ar: "ساعتان تحت الشراع حول إلفنتين وجزيرة النباتات، والمحرك مطفأ طوال الوقت.",
    },
    description: {
      en: "Feluccas have not changed design in centuries and they still do the job better than anything with a motor. The route curls between granite boulders, past the Aga Khan mausoleum on the west bank, and holds still in the middle of the river while the sun goes down.",
      ar: "لم يتغير تصميم الفلوكة منذ قرون، وما زالت تؤدي المهمة أفضل من أي شيء بمحرك. ينساب المسار بين صخور الجرانيت، ويمر بضريح الأغا خان في الضفة الغربية، ويثبت في وسط النهر بينما تغيب الشمس.",
    },
    schedule: { en: "Daily, departing 90 minutes before sunset", ar: "يوميًا، الإبحار قبل الغروب بتسعين دقيقة" },
    meetingPoint: { en: "Corniche felucca mooring, Aswan", ar: "مرسى الفلائك في كورنيش أسوان" },
    inclusions: { en: ["Private or shared felucca with captain", "Hibiscus and water", "Two-hour sail"], ar: ["فلوكة خاصة أو مشتركة مع ربان", "كركديه وماء", "إبحار ساعتين"] },
    exclusions: { en: ["Island entry tickets", "Dinner"], ar: ["تذاكر دخول الجزر", "العشاء"] },
    whatToBring: { en: ["A layer for after sunset", "Cash for the captain's tip"], ar: ["طبقة إضافية لما بعد الغروب", "نقود لإكرامية الربان"] },
    accessibility: { en: "Boarding is a step down into a low open boat with no rail.", ar: "الصعود خطوة نازلة إلى قارب مفتوح منخفض بلا حاجز." },
    cancellation: { en: "Free cancellation up to 12 hours before", ar: "إلغاء مجاني حتى 12 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/felucca.webp", alt: { en: "Feluccas under sail on the Nile", ar: "فلائك تبحر على النيل" } },
    gallery: [],
    accent: "#2c6e67",
  },
  {
    id: "exp-nile-cruise",
    slug: "nile-cruise-aswan-to-luxor",
    name: { en: "Nile Cruise, Aswan to Luxor", ar: "رحلة نيلية من أسوان إلى الأقصر" },
    destinationSlug: "aswan",
    category: "water",
    travelStyles: ["luxury", "romantic", "history"],
    environment: "water",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 4320,
    priceFrom: 590,
    privateSupplement: 0,
    rating: 4.8,
    reviewCount: 388,
    maxGroupSize: 60,
    minAge: null,
    summary: {
      en: "Three nights downstream with Kom Ombo and Edfu on the way, all meals aboard.",
      ar: "ثلاث ليالٍ مع التيار مرورًا بكوم أمبو وإدفو، وجميع الوجبات على المتن.",
    },
    description: {
      en: "The classic river route, and still the most comfortable way to see the temples between the two cities. Kom Ombo is visited at dusk when the light is best, Edfu by horse carriage in the early morning, and the rest of the time the valley simply moves past the sun deck.",
      ar: "المسار النهري الكلاسيكي، وما زال أريح طريقة لرؤية المعابد بين المدينتين. تُزار كوم أمبو عند الغسق حيث يكون الضوء في أفضل حالاته، وإدفو بعربة خيل في الصباح الباكر، وفي بقية الوقت يمر الوادي ببساطة أمام سطح الشمس.",
    },
    schedule: { en: "Departures on set days; four days and three nights", ar: "إبحار في أيام محددة؛ أربعة أيام وثلاث ليالٍ" },
    meetingPoint: { en: "Cruise mooring, Aswan corniche", ar: "مرسى الرحلات النيلية، كورنيش أسوان" },
    inclusions: { en: ["Three nights aboard in an outside cabin", "Full board", "Guided temple visits at Kom Ombo and Edfu", "Onboard Egyptologist"], ar: ["ثلاث ليالٍ على المتن في كابينة خارجية", "إقامة كاملة", "زيارات مرشدة لمعبدي كوم أمبو وإدفو", "عالم مصريات على المتن"] },
    exclusions: { en: ["Drinks", "Optional excursions", "Gratuities for the crew"], ar: ["المشروبات", "الرحلات الاختيارية", "إكراميات الطاقم"] },
    whatToBring: { en: ["A soft bag rather than a hard case", "Smart casual for dinner"], ar: ["حقيبة لينة بدل الصلبة", "ملابس شبه رسمية للعشاء"] },
    accessibility: { en: "Most vessels have no lift between decks and cabin doorways are narrow.", ar: "معظم المراكب بلا مصعد بين الطوابق، وأبواب الكبائن ضيقة." },
    cancellation: { en: "Free cancellation up to 14 days before", ar: "إلغاء مجاني حتى 14 يومًا قبل الموعد" },
    heroImage: { src: "/images/experiences/nile-cruise.webp", alt: { en: "A river cruiser moored on the Nile", ar: "مركب نيلي راسٍ على النهر" } },
    gallery: [],
    accent: "#1f5a7d",
  },
  {
    id: "exp-sand-sea",
    slug: "great-sand-sea-safari",
    name: { en: "Great Sand Sea Safari", ar: "سفاري بحر الرمال الأعظم" },
    destinationSlug: "siwa-oasis",
    category: "adventure",
    travelStyles: ["desert", "nature"],
    environment: "desert",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 330,
    priceFrom: 68,
    privateSupplement: 55,
    rating: 4.9,
    reviewCount: 241,
    maxGroupSize: 6,
    minAge: 8,
    summary: {
      en: "Dune driving, sandboarding, a fossil field and a hot spring, ending with sunset on a high ridge.",
      ar: "قيادة على الكثبان وتزلج على الرمال وحقل أحافير وعين ساخنة، وتنتهي بغروب على حافة عالية.",
    },
    description: {
      en: "A licensed Siwan driver takes a 4x4 into the dune field west of the oasis. You sandboard a few slopes, walk a bed of marine fossils that were a seabed forty million years ago, swim in a hot spring at Bir Wahed, and watch the sun go down from the top of a dune with tea brewing on a fire.",
      ar: "يقود سائق سيوي مرخص سيارة دفع رباعي إلى حقل الكثبان غرب الواحة. تتزلج على بضعة منحدرات، وتمشي على طبقة من الأحافير البحرية التي كانت قاع بحر قبل أربعين مليون سنة، وتسبح في عين ساخنة ببئر وحيد، وتشاهد غياب الشمس من أعلى كثيب والشاي يغلي على النار.",
    },
    schedule: { en: "Daily, 14:00 departure", ar: "يوميًا، الانطلاق 14:00" },
    meetingPoint: { en: "Your Siwa lodge or the town square", ar: "نُزُلك في سيوة أو ميدان البلدة" },
    inclusions: { en: ["Licensed 4x4 and desert driver", "Sandboard hire", "Hot spring stop", "Bedouin tea at sunset"], ar: ["سيارة دفع رباعي مرخصة وسائق صحراوي", "استئجار لوح التزلج", "وقفة في العين الساخنة", "شاي بدوي عند الغروب"] },
    exclusions: { en: ["Dinner", "Towels", "Overnight camping upgrade"], ar: ["العشاء", "المناشف", "ترقية المبيت في مخيم"] },
    whatToBring: { en: ["Swimwear worn under clothing", "A towel", "Something to keep sand out of a camera"], ar: ["ملابس سباحة تحت الملابس", "منشفة", "ما يحمي الكاميرا من الرمل"] },
    accessibility: { en: "Repeated steep dune descents in a vehicle. Not advisable with back or neck injuries or during pregnancy.", ar: "نزول متكرر على كثبان شديدة الانحدار داخل السيارة. غير مستحسن لمن لديه إصابات في الظهر أو الرقبة أو للحوامل." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/sand-sea.webp", alt: { en: "Walking a dune crest at sunset", ar: "سير على قمة كثيب عند الغروب" } },
    gallery: [],
    accent: "#9a7a54",
  },
  {
    id: "exp-siwa-salt",
    slug: "siwa-salt-lake-float",
    name: { en: "Salt Lake Float and Olive Grove Lunch", ar: "طفو في البحيرة الملحية وغداء في بستان زيتون" },
    destinationSlug: "siwa-oasis",
    category: "wellness",
    travelStyles: ["nature", "romantic"],
    environment: "outdoor",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 240,
    priceFrom: 42,
    privateSupplement: 28,
    rating: 4.8,
    reviewCount: 134,
    maxGroupSize: 10,
    minAge: null,
    summary: {
      en: "Float in water so saline you cannot sink, then eat under olive trees at the edge of the oasis.",
      ar: "اطفُ في ماء شديد الملوحة لا يمكنك الغرق فيه، ثم تناول الطعام تحت أشجار الزيتون على أطراف الواحة.",
    },
    description: {
      en: "Siwa's salt pools are old quarry basins with crystalline white edges and water more buoyant than the Dead Sea. The float lasts about twenty minutes before the salt asks you to rinse. Lunch afterwards is olives, dates, flatbread and slow-roasted vegetables in a grove.",
      ar: "برك سيوة الملحية أحواض محاجر قديمة بحواف بلورية بيضاء وماء أشد طفوًا من البحر الميت. يستمر الطفو نحو عشرين دقيقة قبل أن يطلب منك الملح أن تشطف. والغداء بعدها زيتون وتمر وخبز بلدي وخضار مشوية ببطء في بستان.",
    },
    schedule: { en: "Daily, 10:00", ar: "يوميًا، 10:00" },
    meetingPoint: { en: "Your Siwa lodge", ar: "نُزُلك في سيوة" },
    inclusions: { en: ["Transfers within the oasis", "Salt lake access", "Fresh-water rinse", "Grove lunch"], ar: ["الانتقالات داخل الواحة", "دخول البحيرة الملحية", "شطف بالماء العذب", "غداء في البستان"] },
    exclusions: { en: ["Towels", "Massage add-on"], ar: ["المناشف", "إضافة جلسة تدليك"] },
    whatToBring: { en: ["Swimwear you do not mind bleaching", "Sandals", "No fresh shaving cuts"], ar: ["ملابس سباحة لا تمانع تفتّح لونها", "صندل", "تجنب الجروح الحديثة من الحلاقة"] },
    accessibility: { en: "The pool edge is uneven crystallised salt, sharp in places, with no handrail.", ar: "حافة البركة ملح متبلور غير مستوٍ، حاد في بعض المواضع، وبلا مسند يد." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/siwa-salt.webp", alt: { en: "A turquoise salt pool with white banks", ar: "بركة ملحية فيروزية بضفاف بيضاء" } },
    gallery: [],
    accent: "#468a82",
  },
  {
    id: "exp-siwa-bike",
    slug: "siwa-oracle-bike-tour",
    name: { en: "Oracle and Olive Groves by Bicycle", ar: "معبد الوحي والبساتين بالدراجة" },
    destinationSlug: "siwa-oasis",
    category: "nature",
    travelStyles: ["nature", "history", "family"],
    environment: "outdoor",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 210,
    priceFrom: 30,
    privateSupplement: 22,
    rating: 4.7,
    reviewCount: 88,
    maxGroupSize: 8,
    minAge: 12,
    summary: {
      en: "Flat lanes between palm gardens to the Temple of the Oracle and Cleopatra's Spring.",
      ar: "دروب مستوية بين حدائق النخيل إلى معبد الوحي وعين كليوباترا.",
    },
    description: {
      en: "Siwa is best seen from a bicycle: the oasis is flat, the lanes are shaded, and nothing worth reaching is more than four kilometres away. The route takes in the oracle where Alexander was told he was divine, the ruins at Umm Ubayda, and a spring stop before returning through the groves.",
      ar: "أفضل ما تُرى سيوة من على دراجة: الواحة مستوية والدروب مظللة، ولا يبعد شيء يستحق الوصول إليه أكثر من أربعة كيلومترات. يشمل المسار معبد الوحي حيث قيل للإسكندر إنه إله، وأطلال أم عبيدة، ووقفة عند عين قبل العودة عبر البساتين.",
    },
    schedule: { en: "Daily, 09:00 and 15:30", ar: "يوميًا، 09:00 و15:30" },
    meetingPoint: { en: "Siwa town square bicycle stand", ar: "موقف الدراجات في ميدان بلدة سيوة" },
    inclusions: { en: ["Bicycle hire", "Local guide", "Temple entry", "Water"], ar: ["استئجار دراجة", "مرشد محلي", "دخول المعبد", "ماء"] },
    exclusions: { en: ["Helmets, which are not stocked locally", "Spring entry donation"], ar: ["الخوذات، فهي غير متوفرة محليًا", "تبرع دخول العين"] },
    whatToBring: { en: ["Sun hat", "Modest clothing for the village lanes"], ar: ["قبعة شمس", "ملابس محتشمة لدروب القرية"] },
    accessibility: { en: "Requires confident cycling on unpaved lanes. A car alternative is available for the same route.", ar: "يتطلب قيادة واثقة للدراجة على دروب غير معبدة. ويتوفر بديل بالسيارة للمسار نفسه." },
    cancellation: { en: "Free cancellation up to 12 hours before", ar: "إلغاء مجاني حتى 12 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/siwa-bike.webp", alt: { en: "The ruins at Aghurmi beside the Temple of the Oracle", ar: "أطلال أغورمي بجوار معبد الوحي" } },
    gallery: [],
    accent: "#2c6e67",
  },
  {
    id: "exp-white-desert-camp",
    slug: "white-desert-overnight-camp",
    name: { en: "White Desert Overnight Camp", ar: "مبيت في مخيم الصحراء البيضاء" },
    destinationSlug: "white-desert",
    category: "adventure",
    travelStyles: ["desert", "nature", "romantic"],
    environment: "desert",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 1800,
    priceFrom: 180,
    privateSupplement: 140,
    rating: 4.9,
    reviewCount: 176,
    maxGroupSize: 8,
    minAge: 8,
    summary: {
      en: "Sleep among the chalk formations with no light pollution for two hundred kilometres.",
      ar: "نم بين التكوينات الطباشيرية بلا تلوث ضوئي على مدى مئتي كيلومتر.",
    },
    description: {
      en: "Drive out from Bahariya through the Black Desert and Crystal Mountain, then set camp among the white formations in time for sunset. Dinner is cooked over a fire, the sky is as good as any on earth, and desert foxes usually turn up. You wake for first light on the chalk before driving back.",
      ar: "انطلق من الباويطي عبر الصحراء السوداء وجبل الكريستال، ثم انصب المخيم بين التكوينات البيضاء قبل الغروب. يُطهى العشاء على النار، والسماء هنا تضاهي أي سماء على الأرض، وعادة ما تظهر ثعالب الصحراء. وتستيقظ لأول الضوء على الطباشير قبل العودة.",
    },
    schedule: { en: "Daily departures from Bahariya, 13:00", ar: "انطلاق يومي من الباويطي، 13:00" },
    meetingPoint: { en: "Bahariya Oasis, Bawiti village", ar: "واحة الباويطي، قرية الباويطي" },
    inclusions: { en: ["4x4 and desert guide", "Camping equipment and bedding", "Dinner and breakfast", "National park permit"], ar: ["سيارة دفع رباعي ومرشد صحراوي", "معدات التخييم والفرش", "العشاء والفطور", "تصريح المحمية الوطنية"] },
    exclusions: { en: ["Transfer from Cairo", "Alcohol, which is not permitted in the park", "Showers"], ar: ["الانتقال من القاهرة", "الكحول، وهو غير مسموح في المحمية", "الاستحمام"] },
    whatToBring: { en: ["A warm layer, genuinely", "Head torch", "Wet wipes and your own rubbish bag"], ar: ["طبقة دافئة، وهذا جاد", "كشاف رأس", "مناديل مبللة وكيس لنفاياتك"] },
    accessibility: { en: "Camping on sand with a shared tent and a desert toilet. No running water and no step-free facilities.", ar: "تخييم على الرمل بخيمة مشتركة ودورة مياه صحراوية. لا ماء جاريًا ولا مرافق خالية من الدرج." },
    cancellation: { en: "Free cancellation up to 72 hours before", ar: "إلغاء مجاني حتى 72 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/white-desert-camp.webp", alt: { en: "Chalk pillars in the White Desert", ar: "أعمدة طباشيرية في الصحراء البيضاء" } },
    gallery: [],
    accent: "#7c6144",
  },
  {
    id: "exp-giftun",
    slug: "giftun-island-snorkel-day",
    name: { en: "Giftun Island Snorkel Day", ar: "يوم غطس في جزيرة الجفتون" },
    destinationSlug: "hurghada",
    category: "water",
    travelStyles: ["beach", "family", "nature"],
    environment: "water",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 480,
    priceFrom: 46,
    privateSupplement: 260,
    rating: 4.7,
    reviewCount: 934,
    maxGroupSize: 25,
    minAge: null,
    summary: {
      en: "Two reef stops and a sandbank beach, with lunch cooked on the boat.",
      ar: "محطتان على الشعاب وشاطئ رملي، مع غداء يُطهى على المركب.",
    },
    description: {
      en: "The standard Red Sea day out, done properly: a wooden boat rather than a crowded catamaran, two anchorages chosen for coral health rather than convenience, and a stop at the protected sandbank on Giftun's north shore. Guides stay in the water with weaker swimmers.",
      ar: "الرحلة البحرية المعتادة في البحر الأحمر، لكن كما ينبغي: مركب خشبي بدل الكاتاماران المزدحم، ومرسيان مختاران بحسب سلامة الشعاب لا بحسب السهولة، ووقفة عند اللسان الرملي المحمي في شمال الجفتون. ويبقى المرشدون في الماء مع السباحين الأقل خبرة.",
    },
    schedule: { en: "Daily, 08:00 to 16:00", ar: "يوميًا، من 08:00 إلى 16:00" },
    meetingPoint: { en: "Hurghada marina, or hotel pickup", ar: "مارينا الغردقة، أو الانطلاق من الفندق" },
    inclusions: { en: ["Boat with shade and toilets", "Mask, snorkel and fins", "Lunch and soft drinks", "Marine park fee"], ar: ["مركب بمظلة ودورات مياه", "نظارة وأنبوب تنفس وزعانف", "الغداء والمشروبات الغازية", "رسوم المحمية البحرية"] },
    exclusions: { en: ["Wetsuit hire in winter", "Diving supplement", "Gratuities"], ar: ["استئجار بدلة الغوص شتاءً", "إضافة الغوص", "الإكراميات"] },
    whatToBring: { en: ["Reef-safe sunscreen only", "A towel", "A dry bag for your phone"], ar: ["واقي شمس آمن للشعاب فقط", "منشفة", "حقيبة مقاومة للماء للهاتف"] },
    accessibility: { en: "Entry to the water is by ladder from the stern. Crew assistance is available.", ar: "النزول إلى الماء بسُلّم من مؤخرة المركب. وتتوفر مساعدة الطاقم." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/giftun.webp", alt: { en: "Snorkellers over a shallow reef", ar: "غطّاسون فوق شعاب ضحلة" } },
    gallery: [],
    accent: "#2a719a",
  },
  {
    id: "exp-eastern-desert-quad",
    slug: "eastern-desert-quad-and-bedouin-dinner",
    name: { en: "Eastern Desert Quad and Bedouin Dinner", ar: "دراجات رباعية في الصحراء الشرقية وعشاء بدوي" },
    destinationSlug: "hurghada",
    category: "adventure",
    travelStyles: ["desert", "family"],
    environment: "desert",
    groupFormat: ["shared", "private"],
    familyFriendly: true,
    durationMinutes: 300,
    priceFrom: 38,
    privateSupplement: 40,
    rating: 4.5,
    reviewCount: 617,
    maxGroupSize: 20,
    minAge: 6,
    summary: {
      en: "An hour on the quads into the hills, then dinner and stargazing at a Bedouin settlement.",
      ar: "ساعة على الدراجات الرباعية داخل التلال، ثم عشاء ورصد للنجوم في مضرب بدوي.",
    },
    description: {
      en: "The Eastern Desert starts thirty minutes inland and the change is total: no sea, no resorts, just gravel plains and mountains. After the ride there is tea in a Bedouin camp, grilled dinner, a short camel ride for anyone who wants one, and a telescope out once the sky darkens.",
      ar: "تبدأ الصحراء الشرقية على بعد ثلاثين دقيقة نحو الداخل، والتغير كامل: لا بحر ولا منتجعات، بل سهول حصوية وجبال. وبعد الجولة شاي في مخيم بدوي وعشاء مشوي وركوب قصير للجمل لمن يرغب، ومرقاب فلكي حين تظلم السماء.",
    },
    schedule: { en: "Daily, 15:00", ar: "يوميًا، 15:00" },
    meetingPoint: { en: "Hotel pickup in Hurghada", ar: "الانطلاق من فندقك في الغردقة" },
    inclusions: { en: ["Quad bike and helmet", "Bedouin camp dinner", "Camel ride", "Stargazing with a telescope"], ar: ["دراجة رباعية وخوذة", "عشاء في المخيم البدوي", "ركوب جمل", "رصد النجوم بمرقاب"] },
    exclusions: { en: ["Goggles, recommended and sold on site", "Drinks beyond tea and water"], ar: ["النظارات الواقية، ويُنصح بها وتُباع في الموقع", "المشروبات عدا الشاي والماء"] },
    whatToBring: { en: ["Clothes you do not mind covering in dust", "A scarf for your face"], ar: ["ملابس لا تمانع اتساخها بالغبار", "وشاح لوجهك"] },
    accessibility: { en: "Riders must operate the quad themselves. Children ride as passengers with an adult.", ar: "على السائق تشغيل الدراجة بنفسه. ويركب الأطفال كمرافقين مع بالغ." },
    cancellation: { en: "Free cancellation up to 24 hours before", ar: "إلغاء مجاني حتى 24 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/quad-desert.webp", alt: { en: "Quad bikes crossing a desert plain", ar: "دراجات رباعية تعبر سهلًا صحراويًا" } },
    gallery: [],
    accent: "#a94a1b",
  },
  {
    id: "exp-ras-mohammed",
    slug: "ras-mohammed-diving-day",
    name: { en: "Ras Mohammed Diving Day", ar: "يوم غوص في رأس محمد" },
    destinationSlug: "sharm-el-sheikh",
    category: "water",
    travelStyles: ["nature", "beach"],
    environment: "water",
    groupFormat: ["shared", "private"],
    familyFriendly: false,
    durationMinutes: 480,
    priceFrom: 115,
    privateSupplement: 180,
    rating: 4.9,
    reviewCount: 528,
    maxGroupSize: 12,
    minAge: 12,
    summary: {
      en: "Two guided dives at Shark and Yolanda reefs, where the wall drops into open blue.",
      ar: "غوصتان بصحبة مرشد في شعاب شارك ويولاندا، حيث ينحدر الجدار إلى الزرقة المفتوحة.",
    },
    description: {
      en: "Egypt's first national park and still its best diving. Shark Reef and Yolanda Reef sit side by side, the first a sheer wall with schooling barracuda and the second scattered with the cargo of a wreck that slid off the plateau in 1980. Two dives, full guiding, one boat day.",
      ar: "أول محمية وطنية في مصر وما زالت أفضل مواقع الغوص فيها. تقع شعبتا شارك ويولاندا جنبًا إلى جنب، الأولى جدار رأسي فيه أسراب الباراكودا، والثانية مبعثرة بحمولة سفينة انزلقت عن الهضبة عام 1980. غوصتان وإرشاد كامل ويوم بحري واحد.",
    },
    schedule: { en: "Daily, 07:30 to 15:30", ar: "يوميًا، من 07:30 إلى 15:30" },
    meetingPoint: { en: "Travco or Naama Bay jetty", ar: "رصيف ترافكو أو خليج نعمة" },
    inclusions: { en: ["Two guided dives with tanks and weights", "Boat, lunch and drinks", "Marine park fees", "Divemaster in the water"], ar: ["غوصتان بصحبة مرشد مع أسطوانات وأثقال", "المركب والغداء والمشروبات", "رسوم المحمية البحرية", "مرشد غوص في الماء"] },
    exclusions: { en: ["Full equipment hire", "Nitrox", "Insurance"], ar: ["استئجار المعدات الكاملة", "النيتروكس", "التأمين"] },
    whatToBring: { en: ["Certification card and logbook", "Reef-safe sunscreen", "Seasickness tablets if you need them"], ar: ["بطاقة الشهادة ودفتر الغوص", "واقي شمس آمن للشعاب", "أقراص دوار البحر إن كنت تحتاجها"] },
    accessibility: { en: "Open Water certification or above is required. Entry is a giant stride from the platform.", ar: "يلزم الحصول على شهادة المياه المفتوحة أو أعلى. والنزول بخطوة واسعة من المنصة." },
    cancellation: { en: "Free cancellation up to 48 hours before", ar: "إلغاء مجاني حتى 48 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/ras-mohammed.webp", alt: { en: "A blue lagoon on the Sinai coast", ar: "بحيرة زرقاء على ساحل سيناء" } },
    gallery: [],
    accent: "#1f5a7d",
  },
  {
    id: "exp-thistlegorm",
    slug: "thistlegorm-wreck-dive",
    name: { en: "SS Thistlegorm Wreck Dive", ar: "غوص حطام الثيسل غورم" },
    destinationSlug: "sharm-el-sheikh",
    category: "adventure",
    travelStyles: ["nature"],
    environment: "water",
    groupFormat: ["shared"],
    familyFriendly: false,
    durationMinutes: 720,
    priceFrom: 165,
    privateSupplement: 0,
    rating: 4.9,
    reviewCount: 302,
    maxGroupSize: 12,
    minAge: 18,
    summary: {
      en: "A long day out to the 1941 wreck still holding motorcycles, rifles and trucks in its holds.",
      ar: "يوم طويل إلى حطام عام 1941 الذي ما زالت عنابره تحوي دراجات نارية وبنادق وشاحنات.",
    },
    description: {
      en: "The Thistlegorm was bombed at anchor in October 1941 and settled upright in thirty metres, cargo intact. Two dives cover the exterior and then the holds, where Norton motorcycles are still strapped to Bedford trucks. Advanced certification and a minimum of twenty logged dives.",
      ar: "قُصفت الثيسل غورم وهي راسية في أكتوبر 1941 واستقرت معتدلة على عمق ثلاثين مترًا وحمولتها سليمة. تغطي الغوصتان الهيكل الخارجي ثم العنابر حيث ما زالت دراجات نورتون مثبتة على شاحنات بيدفورد. ويلزم تصنيف متقدم وعشرون غوصة مسجلة على الأقل.",
    },
    schedule: { en: "Set days, departing 04:45", ar: "أيام محددة، المغادرة 04:45" },
    meetingPoint: { en: "Sharm marina, dive centre desk", ar: "مارينا شرم، مكتب مركز الغوص" },
    inclusions: { en: ["Two guided wreck dives", "Tanks, weights and boat", "Breakfast and lunch aboard", "Torch hire"], ar: ["غوصتان في الحطام بصحبة مرشد", "الأسطوانات والأثقال والمركب", "الفطور والغداء على المتن", "استئجار كشاف"] },
    exclusions: { en: ["Nitrox", "Full equipment hire", "Dive insurance, which is mandatory"], ar: ["النيتروكس", "استئجار المعدات الكاملة", "تأمين الغوص، وهو إلزامي"] },
    whatToBring: { en: ["Logbook showing 20+ dives", "Advanced Open Water card", "Warm layers for the boat"], ar: ["دفتر غوص يوثق أكثر من عشرين غوصة", "بطاقة المياه المفتوحة المتقدمة", "طبقات دافئة للمركب"] },
    accessibility: { en: "Three hours each way in open water with strong currents on site. Not a beginner dive.", ar: "ثلاث ساعات في كل اتجاه في مياه مفتوحة مع تيارات قوية في الموقع. ليست غوصة للمبتدئين." },
    cancellation: { en: "Free cancellation up to 72 hours before", ar: "إلغاء مجاني حتى 72 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/thistlegorm.webp", alt: { en: "Vehicles in the hold of the Thistlegorm", ar: "مركبات داخل عنبر الثيسل غورم" } },
    gallery: [],
    accent: "#16374b",
  },
  {
    id: "exp-mount-sinai",
    slug: "mount-sinai-sunrise-trek",
    name: { en: "Mount Sinai Sunrise Trek", ar: "تسلق جبل موسى عند الشروق" },
    destinationSlug: "sharm-el-sheikh",
    category: "adventure",
    travelStyles: ["nature", "desert"],
    environment: "outdoor",
    groupFormat: ["shared", "private"],
    familyFriendly: false,
    durationMinutes: 780,
    priceFrom: 72,
    privateSupplement: 95,
    rating: 4.7,
    reviewCount: 359,
    maxGroupSize: 15,
    minAge: 12,
    summary: {
      en: "A night climb to 2,285 metres, sunrise at the summit and St Catherine's Monastery after.",
      ar: "تسلق ليلي إلى ارتفاع 2285 مترًا، وشروق من القمة، ثم دير سانت كاترين بعده.",
    },
    description: {
      en: "Leave Sharm around eleven at night, start walking at two, and reach the summit with an hour to spare before first light. The camel path is gradual; the last 750 steps are cut stone and steep. St Catherine's Monastery opens at nine on the way down.",
      ar: "غادر شرم نحو الحادية عشرة ليلًا، وابدأ السير عند الثانية، وابلغ القمة قبل أول الضوء بساعة. طريق الجمال متدرج، أما الدرجات الأخيرة وعددها 750 فحجر منحوت شديد الانحدار. ويفتح دير سانت كاترين عند التاسعة في طريق العودة.",
    },
    schedule: { en: "Set nights, 23:00 pickup", ar: "ليالٍ محددة، الانطلاق 23:00" },
    meetingPoint: { en: "Hotel pickup in Sharm El Sheikh", ar: "الانطلاق من فندقك في شرم الشيخ" },
    inclusions: { en: ["Transfers and permits", "Bedouin mountain guide", "Monastery visit", "Breakfast on the descent"], ar: ["الانتقالات والتصاريح", "مرشد جبلي بدوي", "زيارة الدير", "فطور أثناء النزول"] },
    exclusions: { en: ["Camel hire on the lower path", "Blanket hire at the summit", "Lunch"], ar: ["استئجار الجمل في المسار السفلي", "استئجار البطانية عند القمة", "الغداء"] },
    whatToBring: { en: ["Head torch", "A real jacket, it is near freezing at the top", "Walking shoes with grip"], ar: ["كشاف رأس", "سترة حقيقية، فالبرد قارس عند القمة", "حذاء مشي بنعل مانع للانزلاق"] },
    accessibility: { en: "Seven hours of walking, the final section on uneven stone steps in the dark. Good fitness required.", ar: "سبع ساعات من السير، ومقطعها الأخير درجات حجرية غير مستوية في الظلام. تتطلب لياقة جيدة." },
    cancellation: { en: "Free cancellation up to 48 hours before", ar: "إلغاء مجاني حتى 48 ساعة قبل الموعد" },
    heroImage: { src: "/images/experiences/mount-sinai.webp", alt: { en: "Sunrise over the Sinai mountains", ar: "شروق الشمس فوق جبال سيناء" } },
    gallery: [],
    accent: "#8a3b17",
  },
];

export const experienceBySlug = new Map(experiences.map((e) => [e.slug, e]));

export const experiencesByDestination = experiences.reduce<Record<string, Experience[]>>(
  (acc, exp) => {
    (acc[exp.destinationSlug] ??= []).push(exp);
    return acc;
  },
  {},
);
