import type { Journey } from "./types";

/** Six curated journeys, each one a working starting point for the trip builder. */
export const journeys: Journey[] = [
  {
    id: "jny-ancient-egypt",
    slug: "ancient-egypt-discovery",
    name: { en: "Ancient Egypt Discovery", ar: "اكتشاف مصر القديمة" },
    tagline: { en: "Cairo, Luxor and Aswan in nine days", ar: "القاهرة والأقصر وأسوان في تسعة أيام" },
    summary: {
      en: "The complete pharaonic route, arranged so the sites get better rather than repetitive. Giza and the Grand Egyptian Museum first, then the Theban west bank, then Philae and Abu Simbel at the far south.",
      ar: "المسار الفرعوني الكامل، مرتب بحيث تتصاعد المواقع بدل أن تتكرر. الجيزة والمتحف المصري الكبير أولًا، ثم الضفة الغربية بطيبة، ثم فيلة وأبو سمبل في أقصى الجنوب.",
    },
    days: 9,
    destinationSlugs: ["cairo", "giza", "luxor", "aswan"],
    stopNights: [1, 2, 2, 4],
    experienceSlugs: ["giza-pyramids-at-sunrise", "grand-egyptian-museum-guided", "saqqara-and-dahshur-day", "islamic-cairo-night-walk", "valley-of-the-kings-private", "luxor-hot-air-balloon", "abu-simbel-sunrise", "nubian-village-lunch", "felucca-sunset-sail"],
    travelStyles: ["history", "family"],
    suggestedTier: "comfort",
    priceFrom: 1980,
    bestSeasonNote: { en: "Best from October to April, when the south is comfortable before ten in the morning.", ar: "الأفضل من أكتوبر إلى أبريل، حين يكون الجنوب مريحًا قبل العاشرة صباحًا." },
    heroImage: { src: "/images/journeys/ancient-egypt.webp", alt: { en: "The avenue of ram sphinxes at Karnak", ar: "طريق الكباش في الكرنك" } },
    outline: [
      { day: 1, title: { en: "Arrive Cairo", ar: "الوصول إلى القاهرة" }, detail: { en: "Airport transfer, an evening to settle, dinner on the river.", ar: "انتقال من المطار، ومساء للاستقرار، وعشاء على النهر." } },
      { day: 2, title: { en: "Giza plateau and the museum", ar: "هضبة الجيزة والمتحف" }, detail: { en: "Plateau at opening, Grand Egyptian Museum after lunch.", ar: "الهضبة عند الفتح، والمتحف المصري الكبير بعد الغداء." } },
      { day: 3, title: { en: "Saqqara, Dahshur, old Cairo", ar: "سقارة ودهشور والقاهرة القديمة" }, detail: { en: "Earlier pyramids in the morning, Al-Muizz Street after dark.", ar: "الأهرامات الأقدم صباحًا، وشارع المعز بعد الغروب." } },
      { day: 4, title: { en: "Fly to Luxor", ar: "الطيران إلى الأقصر" }, detail: { en: "Karnak in the late afternoon, Luxor Temple once it is lit.", ar: "الكرنك في آخر النهار، ومعبد الأقصر حين يُضاء." } },
      { day: 5, title: { en: "West bank", ar: "الضفة الغربية" }, detail: { en: "Balloon at dawn, then the royal tombs and Hatshepsut.", ar: "منطاد عند الفجر، ثم المقابر الملكية وحتشبسوت." } },
      { day: 6, title: { en: "Luxor to Aswan", ar: "من الأقصر إلى أسوان" }, detail: { en: "Edfu and Kom Ombo on the road south, arriving for sunset.", ar: "إدفو وكوم أمبو في الطريق جنوبًا، والوصول عند الغروب." } },
      { day: 7, title: { en: "Philae and the Nubian west bank", ar: "فيلة والضفة النوبية" }, detail: { en: "Temple by boat, village lunch, felucca at sunset.", ar: "المعبد بالقارب، وغداء في القرية، وفلوكة عند الغروب." } },
      { day: 8, title: { en: "Abu Simbel", ar: "أبو سمبل" }, detail: { en: "Pre-dawn run south, back to Aswan by mid-afternoon.", ar: "انطلاق قبل الفجر جنوبًا، والعودة إلى أسوان في منتصف الأصيل." } },
      { day: 9, title: { en: "Departure", ar: "المغادرة" }, detail: { en: "Morning at leisure, flight north to connect home.", ar: "صباح حر، ثم طيران شمالًا للربط مع رحلة العودة." } },
    ],
    accent: "#a8853b",
  },
  {
    id: "jny-luxury-nile",
    slug: "luxury-nile-escape",
    name: { en: "Luxury Nile Escape", ar: "رحلة النيل الفاخرة" },
    tagline: { en: "Seven days, mostly on the water", ar: "سبعة أيام، معظمها على الماء" },
    summary: {
      en: "A slower, quieter Egypt for travellers who would rather see three sites properly than nine in passing. Two nights in Cairo, then a river cruise with a private Egyptologist and suites facing the bank.",
      ar: "مصر أهدأ وأبطأ لمن يفضل رؤية ثلاثة مواقع كما ينبغي على تسعة على عجل. ليلتان في القاهرة، ثم رحلة نهرية مع عالم مصريات خاص وأجنحة تطل على الضفة.",
    },
    days: 7,
    destinationSlugs: ["cairo", "giza", "aswan", "luxor"],
    stopNights: [1, 1, 2, 3],
    experienceSlugs: ["giza-pyramids-at-sunrise", "grand-egyptian-museum-guided", "nile-cruise-aswan-to-luxor", "felucca-sunset-sail", "valley-of-the-kings-private"],
    travelStyles: ["luxury", "romantic", "history"],
    suggestedTier: "luxury",
    priceFrom: 4250,
    bestSeasonNote: { en: "November to March, when the river runs cool in the evening and the decks are usable all day.", ar: "من نوفمبر إلى مارس، حين يبرد النهر مساءً وتكون الأسطح صالحة طوال النهار." },
    heroImage: { src: "/images/journeys/luxury-nile.webp", alt: { en: "Morning mist on the Nile", ar: "ضباب الصباح على النيل" } },
    outline: [
      { day: 1, title: { en: "Cairo, arrival", ar: "القاهرة، الوصول" }, detail: { en: "Private transfer, a suite on the river, dinner reserved.", ar: "انتقال خاص، وجناح على النهر، وعشاء محجوز." } },
      { day: 2, title: { en: "Giza privately", ar: "الجيزة بصحبة خاصة" }, detail: { en: "The plateau at opening with a private Egyptologist, museum in the afternoon.", ar: "الهضبة عند الفتح مع عالم مصريات خاص، والمتحف بعد الظهر." } },
      { day: 3, title: { en: "Fly south and board", ar: "الطيران جنوبًا والصعود" }, detail: { en: "Aswan by air, Philae by boat, then aboard for the first night.", ar: "أسوان جوًا، وفيلة بالقارب، ثم الصعود إلى المركب لأول ليلة." } },
      { day: 4, title: { en: "Kom Ombo at dusk", ar: "كوم أمبو عند الغسق" }, detail: { en: "Sail north through the morning, temple visit as the light drops.", ar: "الإبحار شمالًا طوال الصباح، وزيارة المعبد مع انخفاض الضوء." } },
      { day: 5, title: { en: "Edfu by carriage", ar: "إدفو بعربة الخيل" }, detail: { en: "Early temple visit, then a full day on deck through the valley.", ar: "زيارة مبكرة للمعبد، ثم يوم كامل على السطح عبر الوادي." } },
      { day: 6, title: { en: "Luxor west bank", ar: "الضفة الغربية بالأقصر" }, detail: { en: "Disembark, private tombs tour, last night in a garden suite.", ar: "النزول، وجولة خاصة في المقابر، وليلة أخيرة في جناح على الحديقة." } },
      { day: 7, title: { en: "Departure", ar: "المغادرة" }, detail: { en: "Karnak before the heat, then the flight north.", ar: "الكرنك قبل الحر، ثم الطيران شمالًا." } },
    ],
    accent: "#1f5a7d",
  },
  {
    id: "jny-siwa-desert",
    slug: "siwa-desert-adventure",
    name: { en: "Siwa Desert Adventure", ar: "مغامرة صحراء سيوة" },
    tagline: { en: "Eight days into the Western Desert", ar: "ثمانية أيام في الصحراء الغربية" },
    summary: {
      en: "For travellers who want distance from other travellers. Alexandria's coast, then the long road to Siwa, salt lakes and the Great Sand Sea, a full day's drive across the desert to Bahariya, and a night under the chalk of the White Desert.",
      ar: "لمن يريد مسافة تفصله عن بقية المسافرين. ساحل الإسكندرية، ثم الطريق الطويل إلى سيوة والبحيرات الملحية وبحر الرمال الأعظم، ويوم كامل من القيادة عبر الصحراء إلى الواحات البحرية، وليلة تحت طباشير الصحراء البيضاء.",
    },
    days: 8,
    // Bahariya to Cairo is a five-hour drive that does not pass Fayoum, and a
    // sunrise in the White Desert leaves no room for a nine-hour Fayoum day.
    destinationSlugs: ["alexandria", "siwa-oasis", "white-desert", "cairo"],
    stopNights: [2, 3, 2, 1],
    experienceSlugs: ["alexandria-greco-roman-day", "great-sand-sea-safari", "siwa-salt-lake-float", "siwa-oracle-bike-tour", "white-desert-overnight-camp"],
    travelStyles: ["desert", "nature"],
    suggestedTier: "comfort",
    priceFrom: 1650,
    bestSeasonNote: { en: "October to March. The desert is unusable in high summer and camps close.", ar: "من أكتوبر إلى مارس. الصحراء غير صالحة في أوج الصيف وتغلق المخيمات." },
    heroImage: { src: "/images/journeys/siwa-desert.webp", alt: { en: "Dunes at the edge of the Great Sand Sea", ar: "كثبان على حافة بحر الرمال الأعظم" } },
    outline: [
      { day: 1, title: { en: "Cairo to Alexandria", ar: "من القاهرة إلى الإسكندرية" }, detail: { en: "Train north, an afternoon on the corniche.", ar: "قطار شمالًا، وأصيل على الكورنيش." } },
      { day: 2, title: { en: "Greco-Roman Alexandria", ar: "الإسكندرية اليونانية الرومانية" }, detail: { en: "Catacombs, library and citadel, seafood at the harbour.", ar: "السراديب والمكتبة والقلعة، ومأكولات بحرية عند الميناء." } },
      { day: 3, title: { en: "The road to Siwa", ar: "الطريق إلى سيوة" }, detail: { en: "Coast road to Marsa Matrouh, then inland. A long but scenic day.", ar: "الطريق الساحلي إلى مرسى مطروح، ثم نحو الداخل. يوم طويل لكنه جميل." } },
      { day: 4, title: { en: "The oasis by bicycle", ar: "الواحة بالدراجة" }, detail: { en: "Shali, the oracle, Fatnas island at sunset.", ar: "شالي ومعبد الوحي وجزيرة فطناس عند الغروب." } },
      { day: 5, title: { en: "Great Sand Sea", ar: "بحر الرمال الأعظم" }, detail: { en: "Dune safari, fossil beds, hot spring, dinner under the stars.", ar: "سفاري الكثبان وطبقات الأحافير والعين الساخنة وعشاء تحت النجوم." } },
      { day: 6, title: { en: "Salt lakes, then the desert road", ar: "البحيرات الملحية ثم طريق الصحراء" }, detail: { en: "An early float, then a full day's drive across the desert to Bahariya, arriving for dinner.", ar: "طفو مبكر، ثم يوم كامل من القيادة عبر الصحراء إلى الواحات البحرية، والوصول للعشاء." } },
      { day: 7, title: { en: "White Desert camp", ar: "مخيم الصحراء البيضاء" }, detail: { en: "Black Desert, Crystal Mountain, camp among the chalk.", ar: "الصحراء السوداء وجبل الكريستال والمخيم بين الطباشير." } },
      { day: 8, title: { en: "Sunrise and the road to Cairo", ar: "الشروق وطريق القاهرة" }, detail: { en: "First light on the formations, breakfast at the camp, then the five-hour drive back to the city by mid-afternoon.", ar: "أول الضوء على التكوينات، وفطور في المخيم، ثم خمس ساعات من القيادة إلى المدينة بحلول منتصف الأصيل." } },
    ],
    accent: "#9a7a54",
  },
  {
    id: "jny-red-sea",
    slug: "red-sea-retreat",
    name: { en: "Red Sea Retreat", ar: "خلوة البحر الأحمر" },
    tagline: { en: "Six days of reef, sun and nothing scheduled", ar: "ستة أيام من الشعاب والشمس وبلا جدول" },
    summary: {
      en: "Built around water rather than monuments. Sharm as a base, Ras Mohammed and a wreck day on the boat, a desert evening inland, and enough unplanned hours to make it a holiday rather than a tour.",
      ar: "مبنية على الماء لا على الآثار. شرم قاعدةً، ورأس محمد ويوم حطام على المركب، وأمسية صحراوية في الداخل، وساعات فارغة كافية لتجعلها إجازة لا جولة.",
    },
    days: 6,
    destinationSlugs: ["sharm-el-sheikh"],
    stopNights: [6],
    experienceSlugs: ["ras-mohammed-diving-day", "thistlegorm-wreck-dive", "mount-sinai-sunrise-trek"],
    travelStyles: ["beach", "nature"],
    suggestedTier: "premium",
    priceFrom: 1490,
    bestSeasonNote: { en: "Diveable all year. March to May and September to November are the sweet spots.", ar: "الغوص متاح طوال العام. ومن مارس إلى مايو ومن سبتمبر إلى نوفمبر هي الفترات المثلى." },
    heroImage: { src: "/images/journeys/red-sea.webp", alt: { en: "The Ras Mohammed shore, where the desert meets the sea", ar: "ساحل رأس محمد حيث تلتقي الصحراء بالبحر" } },
    outline: [
      { day: 1, title: { en: "Arrive Sharm", ar: "الوصول إلى شرم" }, detail: { en: "Transfer, check in, an afternoon on the house reef.", ar: "الانتقال والتسجيل وأصيل على شعاب الفندق." } },
      { day: 2, title: { en: "Ras Mohammed", ar: "رأس محمد" }, detail: { en: "Two dives or a snorkel day at Shark and Yolanda.", ar: "غوصتان أو يوم غطس في شارك ويولاندا." } },
      { day: 3, title: { en: "Open day", ar: "يوم مفتوح" }, detail: { en: "Deliberately empty. Beach, spa or a second reef.", ar: "فارغ عن قصد. شاطئ أو منتجع صحي أو شعبة ثانية." } },
      { day: 4, title: { en: "The Thistlegorm", ar: "الثيسل غورم" }, detail: { en: "Early boat to the wreck, back by mid-afternoon.", ar: "مركب مبكر إلى الحطام، والعودة في منتصف الأصيل." } },
      { day: 5, title: { en: "Sinai interior", ar: "داخل سيناء" }, detail: { en: "Coloured Canyon and a Bedouin dinner, or the Mount Sinai climb.", ar: "الوادي الملون وعشاء بدوي، أو تسلق جبل موسى." } },
      { day: 6, title: { en: "Departure", ar: "المغادرة" }, detail: { en: "No diving today. Late checkout and the airport.", ar: "لا غوص اليوم. مغادرة متأخرة ثم المطار." } },
    ],
    accent: "#2a719a",
  },
  {
    id: "jny-family",
    slug: "family-journey",
    name: { en: "Family Journey", ar: "رحلة العائلة" },
    tagline: { en: "Ten days that work for children and adults", ar: "عشرة أيام تناسب الأطفال والكبار" },
    summary: {
      en: "Pyramids and temples paced so nobody melts down, balanced against reef snorkelling and a desert night. Shorter site visits, earlier starts, and a Red Sea half at the end as the reward.",
      ar: "أهرامات ومعابد بإيقاع لا يُنهك أحدًا، متوازنة مع غطس بين الشعاب وليلة في الصحراء. زيارات أقصر وبدايات أبكر، ونصف أخير على البحر الأحمر كمكافأة.",
    },
    days: 10,
    destinationSlugs: ["cairo", "giza", "luxor", "hurghada"],
    stopNights: [1, 2, 2, 5],
    experienceSlugs: ["giza-pyramids-at-sunrise", "grand-egyptian-museum-guided", "khan-el-khalili-food-walk", "luxor-hot-air-balloon", "giftun-island-snorkel-day", "eastern-desert-quad-and-bedouin-dinner"],
    travelStyles: ["family", "history", "beach"],
    suggestedTier: "comfort",
    priceFrom: 1860,
    bestSeasonNote: { en: "School holidays in spring and autumn work best. Avoid July and August in the Nile valley.", ar: "تناسبها العطلات المدرسية في الربيع والخريف. وتجنب يوليو وأغسطس في وادي النيل." },
    heroImage: { src: "/images/journeys/family.webp", alt: { en: "Visitors and camels at the Giza pyramids", ar: "زوار وجمال عند أهرامات الجيزة" } },
    outline: [
      { day: 1, title: { en: "Arrive Cairo", ar: "الوصول إلى القاهرة" }, detail: { en: "Transfer and an early night.", ar: "الانتقال ونوم مبكر." } },
      { day: 2, title: { en: "Pyramids, early", ar: "الأهرامات مبكرًا" }, detail: { en: "Plateau at opening, pool in the afternoon.", ar: "الهضبة عند الفتح، والمسبح بعد الظهر." } },
      { day: 3, title: { en: "Museum and market", ar: "المتحف والسوق" }, detail: { en: "Tutankhamun galleries, then the food walk at Khan el-Khalili.", ar: "قاعات توت عنخ آمون، ثم جولة الطعام في خان الخليلي." } },
      { day: 4, title: { en: "Fly to Luxor", ar: "الطيران إلى الأقصر" }, detail: { en: "Karnak late in the day, dinner by the river.", ar: "الكرنك في آخر النهار، وعشاء بجوار النهر." } },
      { day: 5, title: { en: "Balloon and tombs", ar: "المنطاد والمقابر" }, detail: { en: "Dawn flight, three tombs, then rest.", ar: "طيران عند الفجر، وثلاث مقابر، ثم راحة." } },
      { day: 6, title: { en: "Road to Hurghada", ar: "الطريق إلى الغردقة" }, detail: { en: "Four hours across the Eastern Desert, beach by evening.", ar: "أربع ساعات عبر الصحراء الشرقية، والشاطئ مساءً." } },
      { day: 7, title: { en: "Giftun Island", ar: "جزيرة الجفتون" }, detail: { en: "Boat day, two snorkel stops, lunch aboard.", ar: "يوم بحري ومحطتا غطس وغداء على المتن." } },
      { day: 8, title: { en: "Desert evening", ar: "أمسية صحراوية" }, detail: { en: "Quads and a Bedouin camp with stargazing.", ar: "دراجات رباعية ومخيم بدوي مع رصد النجوم." } },
      { day: 9, title: { en: "Beach day", ar: "يوم الشاطئ" }, detail: { en: "Nothing planned at all.", ar: "بلا أي خطة." } },
      { day: 10, title: { en: "Departure", ar: "المغادرة" }, detail: { en: "Direct flight home or connection via Cairo.", ar: "رحلة مباشرة إلى الوطن أو ربط عبر القاهرة." } },
    ],
    accent: "#c85f26",
  },
  {
    id: "jny-honeymoon",
    slug: "romantic-honeymoon",
    name: { en: "Romantic Honeymoon", ar: "شهر عسل رومانسي" },
    tagline: { en: "Eight days of Nile, desert and quiet", ar: "ثمانية أيام من النيل والصحراء والهدوء" },
    summary: {
      en: "Chosen for the evenings rather than the itinerary: a private felucca at sunset, a balloon at dawn, dinner on the water in Cairo, and a last stretch on the Red Sea with nothing booked.",
      ar: "مختارة من أجل الأمسيات لا من أجل الجدول: فلوكة خاصة عند الغروب، ومنطاد عند الفجر، وعشاء على الماء في القاهرة، ومقطع أخير على البحر الأحمر بلا أي حجز.",
    },
    days: 8,
    destinationSlugs: ["cairo", "giza", "aswan", "luxor", "sharm-el-sheikh"],
    stopNights: [1, 1, 2, 2, 2],
    experienceSlugs: ["giza-pyramids-at-sunrise", "felucca-sunset-sail", "nubian-village-lunch", "luxor-hot-air-balloon", "nile-dinner-cruise-cairo"],
    travelStyles: ["romantic", "luxury"],
    suggestedTier: "premium",
    priceFrom: 2680,
    bestSeasonNote: { en: "October to April. Aswan in particular is at its best in the winter months.", ar: "من أكتوبر إلى أبريل. وأسوان خاصة في أفضل حالاتها في أشهر الشتاء." },
    heroImage: { src: "/images/journeys/honeymoon.webp", alt: { en: "Two feluccas at sunset on the Nile", ar: "فلوكتان عند الغروب على النيل" } },
    outline: [
      { day: 1, title: { en: "Cairo", ar: "القاهرة" }, detail: { en: "Arrival, a river-facing suite, dinner on the water.", ar: "الوصول وجناح مطل على النهر وعشاء على الماء." } },
      { day: 2, title: { en: "Giza at first light", ar: "الجيزة عند أول الضوء" }, detail: { en: "Private guiding on the plateau, afternoon free.", ar: "إرشاد خاص في الهضبة، وبعد الظهر حر." } },
      { day: 3, title: { en: "South to Aswan", ar: "جنوبًا إلى أسوان" }, detail: { en: "Short flight, Philae by boat, private felucca at sunset.", ar: "رحلة قصيرة، وفيلة بالقارب، وفلوكة خاصة عند الغروب." } },
      { day: 4, title: { en: "Nubian west bank", ar: "الضفة النوبية الغربية" }, detail: { en: "Village lunch, a slow afternoon, dinner on the island.", ar: "غداء في القرية، وأصيل هادئ، وعشاء في الجزيرة." } },
      { day: 5, title: { en: "Luxor", ar: "الأقصر" }, detail: { en: "North by road with Kom Ombo on the way.", ar: "شمالًا برًا مع كوم أمبو في الطريق." } },
      { day: 6, title: { en: "Balloon at dawn", ar: "منطاد عند الفجر" }, detail: { en: "Flight over the west bank, then the afternoon at leisure.", ar: "طيران فوق الضفة الغربية، ثم أصيل حر." } },
      { day: 7, title: { en: "Red Sea", ar: "البحر الأحمر" }, detail: { en: "Fly to Sharm, check in, nothing else required.", ar: "الطيران إلى شرم، والتسجيل، ولا شيء آخر مطلوب." } },
      { day: 8, title: { en: "Departure", ar: "المغادرة" }, detail: { en: "A last morning on the reef before the flight.", ar: "صباح أخير على الشعاب قبل الرحلة." } },
    ],
    accent: "#8a3b17",
  },
];

export const journeyBySlug = new Map(journeys.map((j) => [j.slug, j]));
