/**
 * Image pipeline.
 *
 *   node scripts/images/build.mjs
 *
 * Reads the curated selection in `sources.json`, downloads each original from
 * Wikimedia Commons into a local cache, and writes:
 *
 *   public/images/<slot>-<width>.webp   responsive variants
 *   public/images/CREDITS.md            attribution for every photograph
 *   src/generated/images.ts             manifest with sizes and LQIP data URIs
 *
 * The cache means re-running is cheap; delete `.cache/images` to refetch.
 */
import sharp from "sharp";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const sources = JSON.parse(readFileSync(join(root, "scripts/images/sources.json"), "utf8"));
const cacheDir = join(root, ".cache/images");
const outDir = join(root, "public/images");
const UA = "WanderlushEgypt-portfolio/1.0 (portfolio project)";

/** Heroes are shown full-bleed; everything else tops out at card width. */
const HERO = /(^hero\/|-hero$)/;
const HERO_WIDTHS = [640, 1024, 1600, 2400];
const CARD_WIDTHS = [480, 800, 1200];

mkdirSync(cacheDir, { recursive: true });

async function download(slot, urls) {
  const file = join(cacheDir, slot.replaceAll("/", "__") + ".src");
  if (existsSync(file)) return file;
  // Commons only serves a fixed set of thumbnail widths per file, so fall
  // back through smaller renders and finally the original upload.
  let lastError;
  for (const url of urls) {
    try {
      const res = await fetch(url, { headers: { "User-Agent": UA } });
      if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
      writeFileSync(file, Buffer.from(await res.arrayBuffer()));
      return file;
    } catch (error) {
      lastError = error;
    }
  }
  throw new Error(`${slot}: ${lastError?.message ?? "download failed"}`);
}

const manifest = {};
const credits = [];
const entries = Object.entries(sources);

for (const [slot, meta] of entries) {
  const src = await download(meta.alias_of ?? slot, meta.download);
  const image = sharp(src, { failOn: "none" }).rotate();
  const { width: srcW, height: srcH } = await image.metadata();
  const widths = (HERO.test(slot) ? HERO_WIDTHS : CARD_WIDTHS).filter((w) => w <= srcW);
  if (widths.length === 0) widths.push(srcW);

  mkdirSync(join(outDir, dirname(slot)), { recursive: true });
  for (const w of widths) {
    const target = join(outDir, `${slot}-${w}.webp`);
    await sharp(src, { failOn: "none" })
      .rotate()
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: w >= 2000 ? 66 : w >= 1600 ? 72 : 78, effort: 5 })
      .toFile(target);
  }

  // 20px wide blurred placeholder, inlined as a data URI in the manifest.
  const lqipBuf = await sharp(src, { failOn: "none" })
    .rotate()
    .resize({ width: 20 })
    .blur(1.2)
    .webp({ quality: 40 })
    .toBuffer();

  manifest[`/images/${slot}.webp`] = {
    widths,
    width: srcW,
    height: srcH,
    lqip: `data:image/webp;base64,${lqipBuf.toString("base64")}`,
    credit: {
      artist: meta.artist,
      license: meta.license,
      source: meta.source,
    },
  };

  credits.push(
    `| ${slot} | [${meta.title.replace("File:", "")}](${meta.source}) | ${meta.artist} | ${meta.license} |`,
  );
  process.stdout.write(`${slot} (${widths.join("/")})\n`);
}

const header = `# Photography credits

Every photograph on this site comes from Wikimedia Commons and is used under the
licence shown. Attribution is required for the CC BY and CC BY-SA images.

| Slot | File | Photographer | Licence |
| --- | --- | --- | --- |`;
writeFileSync(join(outDir, "CREDITS.md"), `${header}\n${credits.sort().join("\n")}\n`);

mkdirSync(join(root, "src/generated"), { recursive: true });
writeFileSync(
  join(root, "src/generated/images.ts"),
  `// Generated by scripts/images/build.mjs. Do not edit by hand.\n\n` +
    `export interface ImageManifestEntry {\n` +
    `  /** Rendered variant widths, ascending. */\n  widths: number[];\n` +
    `  /** Intrinsic size of the source, used to reserve layout space. */\n` +
    `  width: number;\n  height: number;\n` +
    `  /** 20px blurred placeholder shown until the real file decodes. */\n  lqip: string;\n` +
    `  /** Attribution, required by the CC BY and CC BY-SA licences. */\n` +
    `  credit: { artist: string; license: string; source: string };\n}\n\n` +
    `export const imageManifest: Record<string, ImageManifestEntry> = ${JSON.stringify(manifest, null, 2)};\n`,
);

console.log(`\n${entries.length} images, manifest written`);
