/**
 * Writes size-adjusted fallback faces for the four families, so the system
 * font that paints first occupies the same space as the web font that
 * replaces it. Without this the swap reflows every heading and shifts
 * everything below it.
 *
 * The Latin families have published metrics; the Arabic ones are read from
 * the font files themselves (the static instances kept for the PDF). The
 * metrics tooling only knows Latin glyph widths, so the Arabic width
 * adjustment is approximate, but the line-box overrides are exact, and
 * those are what stop the page jumping.
 *
 *   node scripts/fonts.mjs   →  src/styles/font-fallbacks.css
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createFontStack } from "@capsizecss/core";
import { fromBuffer } from "@capsizecss/unpack";
import inter from "@capsizecss/metrics/inter";
import fraunces from "@capsizecss/metrics/fraunces";
import arial from "@capsizecss/metrics/arial";
import georgia from "@capsizecss/metrics/georgia";
import timesNewRoman from "@capsizecss/metrics/timesNewRoman";

const fromFile = async (path, familyName) => ({ ...(await fromBuffer(readFileSync(new URL(path, import.meta.url)))), familyName });

const stacks = [
  { name: "Inter", metrics: [inter, arial] },
  { name: "Fraunces Variable", metrics: [{ ...fraunces, familyName: "Fraunces Variable" }, georgia] },
  { name: "IBM Plex Sans Arabic", metrics: [await fromFile("../public/fonts/pdf/plex-arabic-400.woff", "IBM Plex Sans Arabic"), arial] },
  { name: "Amiri", metrics: [await fromFile("../public/fonts/pdf/amiri-400.woff", "Amiri"), timesNewRoman] },
];

let css = "/* Generated by scripts/fonts.mjs. Do not edit by hand. */\n";
for (const stack of stacks) {
  const { fontFaces } = createFontStack(stack.metrics);
  css += `\n${fontFaces}\n`;
}
writeFileSync(new URL("../src/styles/font-fallbacks.css", import.meta.url), css);
console.log(css);
