/**
 * Writes size-adjusted fallback faces for the two Latin families, so the
 * system font that paints first occupies the same space as the web font
 * that replaces it. Without this the swap reflows every heading and shifts
 * everything below it.
 *
 *   node scripts/fonts.mjs   →  src/styles/font-fallbacks.css
 */
import { writeFileSync } from "node:fs";
import { createFontStack } from "@capsizecss/core";
import inter from "@capsizecss/metrics/inter";
import fraunces from "@capsizecss/metrics/fraunces";
import arial from "@capsizecss/metrics/arial";
import georgia from "@capsizecss/metrics/georgia";

const stacks = [
  { name: "Inter", metrics: [inter, arial] },
  { name: "Fraunces Variable", metrics: [{ ...fraunces, familyName: "Fraunces Variable" }, georgia] },
];

let css = "/* Generated by scripts/fonts.mjs. Do not edit by hand. */\n";
for (const stack of stacks) {
  const { fontFaces } = createFontStack(stack.metrics);
  css += `\n${fontFaces}\n`;
}
writeFileSync(new URL("../src/styles/font-fallbacks.css", import.meta.url), css);
console.log(css);
